const XLSX=require('xlsx');
const rd=(f,s)=>XLSX.utils.sheet_to_json(XLSX.readFile(f).Sheets[s],{header:1,defval:''}).slice(1).filter(r=>r[0]);
const apr=rd('C:/Users/t.bassam/Desktop/WFM System/My work/OPS/Score Card 2026/4.April 26 SC..xlsx','W1');
const may=rd('C:/Users/t.bassam/Desktop/WFM System/My work/OPS/Score Card 2026/5.May 26 SC..xlsx','W1');
const aprIds=new Set(apr.map(r=>Number(r[1])));
const mayIds=new Set(may.map(r=>Number(r[1])));
const newOnes=may.filter(r=>!aprIds.has(Number(r[1])));
const gone=apr.filter(r=>!mayIds.has(Number(r[1])));
console.log('April roster:',apr.length,'| May roster:',may.length);
console.log('NEW in May ('+newOnes.length+'):',newOnes.map(r=>r[0]+'#'+r[1]).join(', '));
console.log('LEFT (in Apr not May) ('+gone.length+'):',gone.map(r=>r[0]).slice(0,20).join(', '));
