const XLSX=require('xlsx');
const COL1={name:0,empNo:1,loginId:2,fn:3,tl:4,wdPct:5,netPts:6,week:7,qualityAct:8,qualityScore:9,fcrAct:16,fcrScore:17,rtScore:31};
const f='C:/Users/t.bassam/Desktop/WFM System/My work/April SC & May/5.May 26 SC - FILLED.xlsx';
const wb=XLSX.read(require('fs').readFileSync(f),{type:'buffer'});
const sn=wb.SheetNames.find(n=>/SC/i.test(n));const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:null});
const headerRow=12;const hdr=rows[headerRow];
const netIdx=hdr.findIndex(c=>/net\s*point/i.test(String(c??'')));const offset=netIdx-COL1.netPts;
const C=offset?Object.fromEntries(Object.entries(COL1).map(([k,v])=>[k,v+offset])):COL1;
console.log('netIdx='+netIdx+' offset='+offset);
const r=rows[13];
console.log('CORRECTED → name='+JSON.stringify(r[C.name])+' netPts='+JSON.stringify(r[C.netPts])+' week='+JSON.stringify(r[C.week])+' qualityAct='+JSON.stringify(r[C.qualityAct])+' qScore='+JSON.stringify(r[C.qualityScore]));
