import { Injectable, Logger } from '@nestjs/common';
import { DataSource } from 'typeorm';
import { SprinklrSnapshot, SprinklrApiConfig, SprinklrAgent } from './sprinklr.types';

// Names generated by DOM-scraping fallback or Sprinklr widget labels —
// must never be stored as real agent names.
const SYNTHETIC_NAME_PATTERNS = [
  /^(available|unavailable|busy|idle|break|away|offline|unknown)\s*\d*$/i,
  /^agent\s+status/i,
  /^(bio\s*break|prayer(\s*break)?|lunch(\s*break)?|short\s*break|meeting|training|coaching|wrap\s*up)(\s+\d+)?$/i,
  /^(no\s+data|user\s+current\s+status|current\s+status|n\/?a|null|undefined|total|grand\s+total|all\s+agents?|active\s+queue)/i,
];

function isSyntheticName(name: string): boolean {
  if (!name) return true;
  const t = name.trim();
  return SYNTHETIC_NAME_PATTERNS.some(re => re.test(t));
}

// IDs generated by the DOM-scraping fallback ("available_0", "offline_3") — not real agents
function isSyntheticAgent(agent: { agentId?: string; agentName?: string }): boolean {
  const id = agent.agentId || '';
  if (/^(available|unavailable|busy|idle|break|away|offline|unknown)_\d+$/i.test(id)) return true;
  return !!agent.agentName && isSyntheticName(agent.agentName) && !id.match(/^\d/);
}

@Injectable()
export class SprinklrService {
  private readonly logger = new Logger(SprinklrService.name);

  // In-memory cache per tenant: tenantId → latest snapshot
  private readonly snapshotCache = new Map<string, SprinklrSnapshot & { receivedAt: number }>();

  constructor(private readonly dataSource: DataSource) {}

  // ── Receive snapshot from Chrome Extension (or internal poller) ────────────
  async ingestSnapshot(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    const enriched = { ...snapshot, receivedAt: Date.now() };
    this.snapshotCache.set(tenantId, enriched);

    // Persist to DB for history + RTA integration
    await this.persistSnapshot(tenantId, snapshot);

    // Update headcount_intervals with live Sprinklr data
    await this.updateLiveCoverage(tenantId, snapshot);

    // Keep sprinklr_agent_map fresh (email → users → employees lookup)
    await this.upsertAgentMap(tenantId, snapshot.agents || []).catch(() => undefined);

    // Recompute today's daily stats (throttled to once per 5 min)
    void this.maybeRollupToday(tenantId);

    this.logger.log(
      `[${tenantId}] Sprinklr snapshot ingested: ${snapshot.queues.length} queues, ${snapshot.agents.length} agents`,
    );
  }

  // ── Get latest cached snapshot (memory first, DB fallback after restart) ───
  async getLatestSnapshot(tenantId: string) {
    let snap = this.snapshotCache.get(tenantId);

    // Memory cache empty (e.g. backend restarted) → hydrate from DB
    if (!snap) {
      try {
        const rows = await this.dataSource.query(
          `SELECT captured_at, queues_json, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
           ORDER BY captured_at DESC LIMIT 1`,
          [tenantId],
        );
        if (rows?.length) {
          const r = rows[0];
          const parse = (v: any) => (Array.isArray(v) ? v : JSON.parse(v || '[]'));
          snap = {
            source:     'sprinklr',
            capturedAt: r.captured_at,
            queues:     parse(r.queues_json),
            agents:     parse(r.agents_json),
            receivedAt: new Date(r.captured_at).getTime(),
          };
          this.snapshotCache.set(tenantId, snap);
          this.logger.log(`[${tenantId}] Snapshot cache hydrated from DB (captured ${r.captured_at})`);
        }
      } catch (e: any) {
        this.logger.warn(`[${tenantId}] DB snapshot hydration failed: ${e.message}`);
      }
    }

    if (!snap) return null;
    return {
      ...snap,
      staleSec: Math.round((Date.now() - snap.receivedAt) / 1000),
      isStale: Date.now() - snap.receivedAt > 120_000, // > 2 min
    };
  }

  // ── Get queue summary for RTA dashboard ───────────────────────────────────
  async getQueueSummary(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    if (!snap) {
      return {
        capturedAt: null,
        staleSec: 0,
        isStale: true,
        summary: { totalWaiting: 0, totalInProgress: 0, totalAvailable: 0, totalBusy: 0, avgSla: 100 },
        atRisk: [],
        queues: [],
        agents: [],
      };
    }

    // Filter out DOM-scraping artefacts (date-range text picked up as queue name)
    const queues = snap.queues.filter(q =>
      q.queueName &&
      !/^Selected date/i.test(q.queueName) &&
      !/^\d{2}\/\d{2}\/\d{4}/.test(q.queueName) &&
      q.queueName.length < 100,
    );

    const totalWaiting   = queues.reduce((s, q) => s + q.waiting, 0);
    const totalInProgress= queues.reduce((s, q) => s + q.inProgress, 0);
    const totalAvailable = queues.reduce((s, q) => s + q.agentsAvailable, 0);
    const totalBusy      = queues.reduce((s, q) => s + q.agentsBusy, 0);
    const avgSla         = queues.length
      ? queues.reduce((s, q) => s + (q.slaPct ?? 100), 0) / queues.length
      : 100;

    const atRisk = queues.filter(q => (q.slaPct ?? 100) < 80);

    return {
      capturedAt: snap.capturedAt,
      staleSec:   snap.staleSec,
      isStale:    snap.isStale,
      summary: { totalWaiting, totalInProgress, totalAvailable, totalBusy, avgSla: +avgSla.toFixed(1) },
      atRisk,
      queues,
      agents:  snap.agents,
    };
  }

  // ── Direct Sprinklr API poller (used when API key is available) ────────────
  async pollFromApi(tenantId: string): Promise<void> {
    const config = await this.getApiConfig(tenantId);
    if (!config?.apiKey) {
      this.logger.warn(`[${tenantId}] No Sprinklr API key configured`);
      return;
    }

    try {
      const snapshot = await this.fetchFromSprinklrApi(config);
      await this.ingestSnapshot(tenantId, snapshot);
    } catch (e: any) {
      this.logger.error(`[${tenantId}] Sprinklr API poll failed: ${e.message}`);
    }
  }

  // ── Sprinklr REST API calls ────────────────────────────────────────────────
  private async fetchFromSprinklrApi(config: SprinklrApiConfig): Promise<SprinklrSnapshot> {
    const headers = {
      'key':          config.apiKey,
      'X-PARTNER-ID': config.partnerId,
      'Content-Type': 'application/json',
    };

    // Sprinklr API v2 endpoints for queue monitoring
    const [queuesRes, agentsRes] = await Promise.allSettled([
      fetch(`${config.baseUrl}/api/v2/${config.environmentId}/listening/stream`, { headers }),
      fetch(`${config.baseUrl}/api/v2/${config.environmentId}/monitoring/agent-status`, { headers }),
    ]);

    const queues = queuesRes.status === 'fulfilled' && queuesRes.value.ok
      ? await queuesRes.value.json().then(d => this.mapSprinklrQueues(d)).catch(() => [])
      : [];

    const agents = agentsRes.status === 'fulfilled' && agentsRes.value.ok
      ? await agentsRes.value.json().then(d => this.mapSprinklrAgents(d)).catch(() => [])
      : [];

    return {
      source: 'api',
      capturedAt: new Date().toISOString(),
      queues,
      agents,
    };
  }

  private mapSprinklrQueues(raw: any): SprinklrSnapshot['queues'] {
    const list = Array.isArray(raw) ? raw : (raw?.data ?? raw?.results ?? raw?.queues ?? []);
    return list.map((q: any) => ({
      queueId:         q.id          || q.channelId   || q.streamId   || '',
      queueName:       q.name        || q.label        || q.title      || '',
      channel:         this.mapChannel(q.channelType   || q.type       || ''),
      waiting:         q.waitingCount|| q.inQueue      || 0,
      inProgress:      q.activeCount || q.engaged      || 0,
      backlog:         q.totalOpen   || 0,
      avgWaitSeconds:  q.avgWaitTime || 0,
      slaBreached:     q.slaBreached || 0,
      slaPct:          q.slaCompliance ?? q.slaPct ?? 100,
      agentsAvailable: q.availableAgents ?? 0,
      agentsBusy:      q.busyAgents ?? 0,
      agentsBreak:     q.breakAgents ?? 0,
      aht:             q.aht ?? 0,
    }));
  }

  private mapSprinklrAgents(raw: any): SprinklrSnapshot['agents'] {
    const list = Array.isArray(raw) ? raw : (raw?.data ?? raw?.users ?? raw?.agents ?? []);
    return list.map((a: any) => ({
      agentId:        a.userId      || a.agentId     || a.id     || '',
      agentName:      a.userName    || a.displayName || a.name   || '',
      status:         this.mapAgentStatus(a.status   || a.availability || ''),
      currentChannel: this.mapChannel(a.channelType || ''),
      queueId:        a.queueId    || a.channelId   || '',
      loginTime:      a.loginTime  || '',
    }));
  }

  private mapChannel(raw: string): SprinklrSnapshot['queues'][0]['channel'] {
    const s = (raw || '').toLowerCase();
    if (s.includes('whatsapp') || s.includes('wa')) return 'whatsapp';
    if (s.includes('chat'))    return 'chat';
    if (s.includes('email'))   return 'email';
    if (s.includes('social') || s.includes('twitter') || s.includes('instagram')) return 'social';
    if (s.includes('voice') || s.includes('call'))  return 'voice';
    return 'unknown';
  }

  private mapAgentStatus(raw: string): SprinklrSnapshot['agents'][0]['status'] {
    const s = (raw || '').toLowerCase();
    if (s.includes('available') || s.includes('online')) return 'available';
    if (s.includes('busy') || s.includes('engaged'))     return 'busy';
    if (s.includes('break'))                             return 'break';
    if (s.includes('away') || s.includes('wrap'))        return 'away';
    if (s.includes('offline'))                           return 'offline';
    return 'unknown';
  }

  // ── Persist snapshot to DB (integration_snapshots table) ──────────────────
  private async persistSnapshot(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    try {
      await this.dataSource.query(
        `INSERT INTO integration_snapshots
           (tenant_id, source, captured_at, queues_json, agents_json, queue_count, agent_count)
         VALUES ($1, 'sprinklr', $2::timestamptz, $3::jsonb, $4::jsonb, $5, $6)`,
        [
          tenantId,
          snapshot.capturedAt,
          JSON.stringify(snapshot.queues),
          JSON.stringify(snapshot.agents),
          snapshot.queues.length,
          snapshot.agents.length,
        ],
      );
    } catch {
      // Table may not exist yet — non-fatal
    }
  }

  // ── Update headcount_intervals with live agent counts from Sprinklr ────────
  private async updateLiveCoverage(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    const now = new Date();
    const hh  = String(now.getHours()).padStart(2, '0');
    const mm  = Math.floor(now.getMinutes() / 15) * 15;
    const intervalStart = `${hh}:${String(mm).padStart(2, '0')}`;

    const totalAvailable = snapshot.agents.filter(a => a.status === 'available').length;
    const totalBusy      = snapshot.agents.filter(a => a.status === 'busy').length;
    const liveHc         = totalAvailable + totalBusy;

    if (liveHc === 0) return;

    try {
      await this.dataSource.query(
        `UPDATE headcount_intervals
         SET live_hc = $1, live_updated_at = NOW()
         WHERE tenant_id = $2
           AND snapshot_date = CURRENT_DATE
           AND interval_start = $3::time`,
        [liveHc, tenantId, intervalStart],
      );
    } catch {
      // headcount_intervals may not have live_hc column yet — non-fatal
    }
  }

  // ── Config management ──────────────────────────────────────────────────────
  async getApiConfig(tenantId: string): Promise<SprinklrApiConfig | null> {
    try {
      const [row] = await this.dataSource.query(
        `SELECT setting_value FROM tenant_settings
         WHERE tenant_id = $1 AND setting_key = 'sprinklr_api_config'`,
        [tenantId],
      );
      if (!row) return null;
      const v = row.setting_value;
      return typeof v === 'object' ? v : JSON.parse(v);
    } catch {
      return null;
    }
  }

  async saveApiConfig(tenantId: string, config: SprinklrApiConfig): Promise<void> {
    await this.dataSource.query(
      `INSERT INTO tenant_settings (tenant_id, setting_key, setting_value, setting_group, updated_at)
       VALUES ($1, 'sprinklr_api_config', $2::jsonb, 'integrations', NOW())
       ON CONFLICT (tenant_id, setting_key) DO UPDATE SET setting_value = $2::jsonb, updated_at = NOW()`,
      [tenantId, JSON.stringify(config)],
    );
  }

  // ── Historical snapshots ───────────────────────────────────────────────────
  async getHistory(tenantId: string, hours = 24) {
    try {
      return this.dataSource.query(
        `SELECT id, source, captured_at, queue_count, agent_count
         FROM integration_snapshots
         WHERE tenant_id = $1 AND source = 'sprinklr'
           AND captured_at >= NOW() - ($2 || ' hours')::interval
         ORDER BY captured_at DESC
         LIMIT 200`,
        [tenantId, hours],
      );
    } catch {
      return [];
    }
  }

  // ── Break Tracker ──────────────────────────────────────────────────────────
  async getBreakTracker(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    const onBreakNow = snap?.agents.filter(a => a.status === 'break' || a.status === 'away') ?? [];

    const [agentHistory, activePermissions] = await Promise.all([
      this.computeBreakHistory(tenantId, 10),
      this.getActivePermissions(tenantId),
    ]);

    const permissionNames = activePermissions.map(p =>
      (p.employee_name || '').toLowerCase(),
    );

    const enriched = onBreakNow.map(a => {
      const hist = agentHistory.find(h => h.agentId === a.agentId);
      const nameLower = (a.agentName || '').toLowerCase();
      const isAuthorized = permissionNames.some(pn =>
        pn && nameLower && (pn.includes(nameLower.slice(0, 6)) || nameLower.includes(pn.slice(0, 6))),
      );
      return {
        ...a,
        isAuthorized,
        breakCount: hist?.breakCount ?? 0,
        totalBreakMinutes: hist?.totalBreakMinutes ?? 0,
        lastBreakStart: hist?.lastBreakStart ?? null,
        currentlyBreaking: true,
      };
    });

    return {
      capturedAt: snap?.capturedAt ?? null,
      onBreakNow: enriched,
      unauthorizedCount: enriched.filter(a => !a.isAuthorized).length,
      authorizedCount:   enriched.filter(a => a.isAuthorized).length,
      agentHistory,
      activePermissions,
    };
  }

  private async computeBreakHistory(tenantId: string, hours: number) {
    try {
      const snapshots: { captured_at: string; agents_json: any }[] =
        await this.dataSource.query(
          `SELECT captured_at, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
             AND captured_at >= NOW() - ($2 || ' hours')::interval
           ORDER BY captured_at ASC
           LIMIT 600`,
          [tenantId, hours],
        );

      if (!snapshots.length) return [];

      const agentTimeline: Record<string, {
        name: string;
        breakCount: number;
        totalBreakMinutes: number;
        lastBreakStart: string | null;
        currentlyBreaking: boolean;
        breaks: { start: string; end: string; minutes: number }[];
        loginTime: string | null;
      }> = {};
      const prevStatus: Record<string, string> = {};

      for (const snap of snapshots) {
        const agents: any[] = Array.isArray(snap.agents_json)
          ? snap.agents_json
          : JSON.parse(snap.agents_json || '[]');
        const ts = snap.captured_at;

        for (const agent of agents) {
          if (!agent.agentId) continue;
          if (isSyntheticAgent(agent)) continue; // skip DOM-scrape placeholder rows
          if (!agentTimeline[agent.agentId]) {
            const initName = (agent.agentName && !isSyntheticName(agent.agentName)) ? agent.agentName : agent.agentId;
            agentTimeline[agent.agentId] = {
              name: initName,
              breakCount: 0,
              totalBreakMinutes: 0,
              lastBreakStart: null,
              currentlyBreaking: false,
              breaks: [],
              loginTime: agent.loginTime || null,
            };
          } else if (agent.agentName && !isSyntheticName(agent.agentName)) {
            // Update name if we now have a real one
            agentTimeline[agent.agentId].name = agent.agentName;
          }
          const prev = prevStatus[agent.agentId];
          const curr = agent.status || 'unknown';
          const timeline = agentTimeline[agent.agentId];
          const isBreak = curr === 'break' || curr === 'away';
          const wasBreak = prev === 'break' || prev === 'away';

          if (isBreak && !wasBreak) {
            timeline.breakCount++;
            timeline.lastBreakStart = ts;
            timeline.currentlyBreaking = true;
          } else if (!isBreak && wasBreak && timeline.lastBreakStart) {
            const start = new Date(timeline.lastBreakStart);
            const end   = new Date(ts);
            const mins  = Math.max(0, Math.round((end.getTime() - start.getTime()) / 60000));
            timeline.breaks.push({ start: timeline.lastBreakStart, end: ts, minutes: mins });
            timeline.totalBreakMinutes += mins;
            timeline.currentlyBreaking = false;
            timeline.lastBreakStart = null;
          }
          prevStatus[agent.agentId] = curr;
        }
      }

      return Object.entries(agentTimeline).map(([agentId, data]) => ({ agentId, ...data }));
    } catch {
      return [];
    }
  }

  // ── Active Permissions ─────────────────────────────────────────────────────
  async getActivePermissions(tenantId: string) {
    try {
      return this.dataSource.query(
        `SELECT r.id, e.full_name AS employee_name, e.employee_no,
                pr.starts_at, pr.ends_at, pr.reason,
                r.status, r.approved_at,
                f.name AS function_name
         FROM requests r
         JOIN permission_requests pr ON pr.request_id = r.id
         JOIN employees e ON e.id = r.employee_id
         LEFT JOIN functions f ON f.id = e.function_id
         WHERE r.tenant_id = $1
           AND r.status = 'approved'
           AND pr.starts_at <= NOW()
           AND pr.ends_at >= NOW()
         ORDER BY pr.starts_at`,
        [tenantId],
      );
    } catch {
      return [];
    }
  }

  // ── Queue Detail ───────────────────────────────────────────────────────────
  async getQueueDetail(tenantId: string, queueId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    if (!snap) return null;

    const queue = snap.queues.find(q => q.queueId === queueId);
    if (!queue) return null;

    const queueAgents = snap.agents.filter(a => a.queueId === queueId);
    const allAgents   = snap.agents;

    // Overflow: available agents NOT in this queue
    const overflow = allAgents
      .filter(a => a.status === 'available' && a.queueId !== queueId)
      .slice(0, 10);

    return {
      queue,
      agents: queueAgents,
      overflow,
      capturedAt: snap.capturedAt,
      staleSec: snap.staleSec,
    };
  }

  // ── Coverage Comparison (Schedule vs Live) ────────────────────────────────
  async getCoverageComparison(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);

    const liveSprinklr = snap ? {
      available:    snap.agents.filter(a => a.status === 'available').length,
      busy:         snap.agents.filter(a => a.status === 'busy').length,
      onBreak:      snap.agents.filter(a => a.status === 'break' || a.status === 'away').length,
      offline:      snap.agents.filter(a => a.status === 'offline' || a.status === 'unknown').length,
      totalLoggedIn: snap.agents.filter(a => a.status !== 'offline' && a.status !== 'unknown').length,
    } : null;

    const [intervals, attendance, activePermCount] = await Promise.all([
      this.dataSource.query(
        `SELECT interval_start::text, function_id,
                COALESCE(required_hc, 0) AS required_hc,
                COALESCE(scheduled_hc, 0) AS scheduled_hc,
                COALESCE(live_hc, 0) AS live_hc
         FROM headcount_intervals
         WHERE tenant_id = $1 AND snapshot_date = CURRENT_DATE
         ORDER BY interval_start`,
        [tenantId],
      ).catch(() => []),

      this.dataSource.query(
        `SELECT
           COUNT(*) FILTER (WHERE punch_in IS NOT NULL) AS punched_in,
           COUNT(*) AS total_scheduled
         FROM attendance_records
         WHERE tenant_id = $1 AND attendance_date = CURRENT_DATE`,
        [tenantId],
      ).catch(() => [{}]),

      this.dataSource.query(
        `SELECT COUNT(*) AS cnt
         FROM requests r
         JOIN permission_requests pr ON pr.request_id = r.id
         WHERE r.tenant_id = $1 AND r.status = 'approved'
           AND pr.starts_at <= NOW() AND pr.ends_at >= NOW()`,
        [tenantId],
      ).catch(() => [{ cnt: 0 }]),
    ]);

    return {
      intervals,
      attendance: attendance[0] ?? { punched_in: 0, total_scheduled: 0 },
      onPermission: +(activePermCount[0]?.cnt ?? 0),
      liveSprinklr,
      capturedAt: snap?.capturedAt ?? null,
    };
  }

  // ── Agent Timeline (working hours tracker) ────────────────────────────────
  async getAgentTimeline(tenantId: string, hours = 10) {
    try {
      const snapshots: { captured_at: string; agents_json: any }[] =
        await this.dataSource.query(
          `SELECT captured_at, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
             AND captured_at >= NOW() - ($2 || ' hours')::interval
           ORDER BY captured_at ASC
           LIMIT 500`,
          [tenantId, hours],
        );

      if (!snapshots.length) return [];

      const agentMap: Record<string, {
        name: string;
        firstSeen: string;
        lastSeen: string;
        statusMinutes: Record<string, number>;
        loginTime: string | null;
      }> = {};

      for (let i = 1; i < snapshots.length; i++) {
        const prev = snapshots[i - 1];
        const curr = snapshots[i];
        const gapMinutes = (new Date(curr.captured_at).getTime() - new Date(prev.captured_at).getTime()) / 60000;
        if (gapMinutes > 5) continue; // skip large gaps (extension was closed)

        const agents: any[] = Array.isArray(curr.agents_json)
          ? curr.agents_json
          : JSON.parse(curr.agents_json || '[]');

        for (const a of agents) {
          if (!a.agentId) continue;
          if (isSyntheticAgent(a)) continue; // skip DOM-scrape placeholder rows
          if (!agentMap[a.agentId]) {
            const initName = (a.agentName && !isSyntheticName(a.agentName)) ? a.agentName : a.agentId;
            agentMap[a.agentId] = {
              name: initName,
              firstSeen: prev.captured_at,
              lastSeen: curr.captured_at,
              statusMinutes: {},
              loginTime: a.loginTime || null,
            };
          }
          const ag = agentMap[a.agentId];
          ag.lastSeen = curr.captured_at;
          // Only accept real names — reject DOM-scraping synthetic names
          if (a.agentName && !isSyntheticName(a.agentName)) {
            ag.name = a.agentName;
          }
          const st = a.status || 'unknown';
          ag.statusMinutes[st] = (ag.statusMinutes[st] ?? 0) + gapMinutes;
        }
      }

      return Object.entries(agentMap).map(([agentId, d]) => {
        // idle = available but not handling conversations → counts as working time (agent IS logged in)
        // In Sprinklr, 'available' = ready but not on a case → WFM idle
        // 'busy' = actively handling a case → WFM working
        const idleMins    = (d.statusMinutes['available'] ?? 0) + (d.statusMinutes['idle'] ?? 0);
        const busyMins    = (d.statusMinutes['busy']      ?? 0);
        const workingMins = idleMins + busyMins;
        const breakMins   = (d.statusMinutes['break'] ?? 0) + (d.statusMinutes['away'] ?? 0);
        const totalMins   = Object.values(d.statusMinutes).reduce((s, v) => s + v, 0);
        return {
          agentId,
          name: d.name,
          // loginTime from snapshot if captured, otherwise use firstSeen as proxy
          loginTime: d.loginTime || d.firstSeen,
          firstSeen: d.firstSeen,
          lastSeen: d.lastSeen,
          workingMinutes: Math.round(workingMins),
          idleMinutes:    Math.round(idleMins),
          busyMinutes:    Math.round(busyMins),
          breakMinutes:   Math.round(breakMins),
          totalTrackedMinutes: Math.round(totalMins),
          utilizationPct: totalMins > 0 ? Math.round((busyMins / totalMins) * 100) : 0,
          statusMinutes: Object.fromEntries(
            Object.entries(d.statusMinutes).map(([k, v]) => [k, Math.round(v)]),
          ),
        };
      }).sort((a, b) => b.workingMinutes - a.workingMinutes);
    } catch {
      return [];
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  AGENT ↔ EMPLOYEE MAPPING (lookup by email: sprinklr → users → employees)
  // ═══════════════════════════════════════════════════════════════════════════
  /**
   * Resolve a Sprinklr agent to a system employee.
   * 1. Exact: users.email → users.employee_id (when the agent has a WFM account).
   * 2. Heuristic (dual-signal, NOT name-alone): corporate email pattern
   *    f.lastname@boutiqaat.com — first initial + surname must BOTH match the
   *    employee record, and the match must be unique.
   */
  private async resolveEmployeeId(tenantId: string, email: string, agentName: string): Promise<string | null> {
    if (!email) return null;

    const rows = await this.dataSource.query(
      `SELECT employee_id FROM users
       WHERE tenant_id = $1 AND lower(email) = lower($2) AND employee_id IS NOT NULL LIMIT 1`,
      [tenantId, email],
    );
    if (rows?.length) return rows[0].employee_id;

    const m = email.toLowerCase().match(/^([a-z])\.([a-z]+)@/);
    if (!m) return null;
    const [, initial, emailLast] = m;

    // Initial must match first name; full normalized name must end with the email surname
    // (handles split surnames like "Abeer Al" + "shemari" → abeeralshemari ends with alshemari)
    const cand = await this.dataSource.query(
      `SELECT id, lower(first_name_en) AS fn FROM employees
       WHERE tenant_id = $1
         AND lower(left(first_name_en, 1)) = $2
         AND regexp_replace(lower(coalesce(first_name_en,'') || coalesce(last_name_en,'')), '[^a-z]', '', 'g')
             LIKE '%' || $3`,
      [tenantId, initial, emailLast],
    );
    if (cand?.length === 1) return cand[0].id;

    // Multiple candidates → disambiguate with the agent's display first name
    if (cand?.length > 1 && agentName) {
      const firstWord = agentName.trim().split(/\s+/)[0].toLowerCase();
      const exact = cand.filter((c: any) => c.fn === firstWord);
      if (exact.length === 1) return exact[0].id;
    }

    // Reversed corporate pattern: lastInitial.firstname@ (e.g. "Saleh Hassan" → h.saleh@)
    // Initial must match the LAST name; email surname part must equal the first name.
    const rev = await this.dataSource.query(
      `SELECT id FROM employees
       WHERE tenant_id = $1
         AND lower(left(coalesce(last_name_en, first_name_en), 1)) = $2
         AND regexp_replace(lower(coalesce(first_name_en,'')), '[^a-z]', '', 'g') = $3`,
      [tenantId, initial, emailLast],
    );
    if (rev?.length === 1) return rev[0].id;

    return null;
  }

  private async upsertAgentMap(tenantId: string, agents: SprinklrAgent[]): Promise<void> {
    const real = agents.filter(a =>
      a.agentId && /^\d{4,}$/.test(a.agentId) &&
      a.agentName && !isSyntheticName(a.agentName),
    );
    for (const a of real) {
      try {
        // Resolve user/employee by email when available
        let userId: string | null = null;
        let employeeId: string | null = null;
        if (a.email) {
          const rows = await this.dataSource.query(
            `SELECT id, employee_id FROM users
             WHERE tenant_id = $1 AND lower(email) = lower($2) LIMIT 1`,
            [tenantId, a.email],
          );
          if (rows?.length) { userId = rows[0].id; employeeId = rows[0].employee_id; }
          if (!employeeId) {
            employeeId = await this.resolveEmployeeId(tenantId, a.email, a.agentName);
          }
        }
        await this.dataSource.query(
          `INSERT INTO sprinklr_agent_map
             (tenant_id, sprinklr_agent_id, agent_name, agent_email, user_id, employee_id, last_seen)
           VALUES ($1, $2, $3, NULLIF($4,''), $5, $6, NOW())
           ON CONFLICT (tenant_id, sprinklr_agent_id) DO UPDATE SET
             agent_name  = EXCLUDED.agent_name,
             agent_email = COALESCE(EXCLUDED.agent_email, sprinklr_agent_map.agent_email),
             user_id     = COALESCE(EXCLUDED.user_id,     sprinklr_agent_map.user_id),
             employee_id = COALESCE(EXCLUDED.employee_id, sprinklr_agent_map.employee_id),
             last_seen   = NOW()`,
          [tenantId, a.agentId, a.agentName, a.email || '', userId, employeeId],
        );
      } catch (e: any) {
        this.logger.warn(`Agent map upsert failed for ${a.agentId}: ${e.message}`);
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  DAILY ROLLUP — per-agent stats computed from the snapshot timeline
  // ═══════════════════════════════════════════════════════════════════════════
  // Sprinklr measurement keys vary by widget; map them heuristically.
  private pickMetric(metrics: Record<string, number>, patterns: RegExp[]): number | null {
    for (const re of patterns) {
      for (const [k, v] of Object.entries(metrics)) {
        if (re.test(k) && typeof v === 'number' && v >= 0) return v;
      }
    }
    return null;
  }

  // Sprinklr times often come in milliseconds — normalize to seconds.
  private toSeconds(v: number | null): number | null {
    if (v == null) return null;
    return v > 100_000 ? Math.round(v / 1000) : Math.round(v);
  }

  async computeDailyStats(tenantId: string, date: string): Promise<{ agents: number }> {
    // Kuwait operational day boundaries (UTC+3)
    const dayStart = `${date}T00:00:00+03:00`;
    const dayEnd   = `${date}T23:59:59.999+03:00`;

    const snapshots: { captured_at: string; agents_json: any }[] =
      await this.dataSource.query(
        `SELECT captured_at, agents_json
         FROM integration_snapshots
         WHERE tenant_id = $1 AND source = 'sprinklr'
           AND captured_at BETWEEN $2::timestamptz AND $3::timestamptz
         ORDER BY captured_at ASC`,
        [tenantId, dayStart, dayEnd],
      );

    if (!snapshots.length) return { agents: 0 };

    type Acc = {
      name: string; email: string;
      firstLogin: string | null; lastLogout: string | null;
      statusMinutes: Record<string, number>;
      rawBreakdown: Record<string, number>;   // tea/lunch/bio/prayer/meeting/manual_dial/other_break
      idleNoCase: number; idleWithCase: number;
      lastMetrics: Record<string, number>;
    };
    const acc: Record<string, Acc> = {};

    // Categorize raw Sprinklr status labels into break/meeting/dial buckets
    const breakCategory = (raw: string, canonical: string): string | null => {
      const s = (raw || '').toLowerCase();
      if (s.includes('bio'))                                return 'bio_break';
      if (s.includes('lunch'))                              return 'lunch_break';
      if (s.includes('tea') || s.includes('short'))         return 'tea_break';
      if (s.includes('prayer'))                             return 'prayer_break';
      if (s.includes('meeting') || s.includes('huddle'))    return 'meeting';
      if (s.includes('training') || s.includes('coach'))    return 'training';
      if (s.includes('manual') || s.includes('outbound') || s.includes('dial')) return 'manual_dial';
      if (s.includes('break'))                              return 'other_break';
      if (canonical === 'break' || canonical === 'away')    return 'other_break';
      return null;
    };

    for (let i = 1; i < snapshots.length; i++) {
      const prev = snapshots[i - 1];
      const curr = snapshots[i];
      const gapMinutes = (new Date(curr.captured_at).getTime() - new Date(prev.captured_at).getTime()) / 60000;
      if (gapMinutes > 5) continue;

      const agents: any[] = Array.isArray(curr.agents_json)
        ? curr.agents_json : JSON.parse(curr.agents_json || '[]');

      for (const a of agents) {
        if (!a.agentId || isSyntheticAgent(a)) continue;
        if (!acc[a.agentId]) {
          acc[a.agentId] = {
            name: (a.agentName && !isSyntheticName(a.agentName)) ? a.agentName : a.agentId,
            email: a.email || '',
            firstLogin: null, lastLogout: null,
            statusMinutes: {}, rawBreakdown: {}, idleNoCase: 0, idleWithCase: 0,
            lastMetrics: {},
          };
        }
        const g = acc[a.agentId];
        if (a.agentName && !isSyntheticName(a.agentName)) g.name = a.agentName;
        if (a.email) g.email = a.email;
        if (a.metrics) g.lastMetrics = { ...g.lastMetrics, ...a.metrics };

        const st = a.status || 'unknown';
        g.statusMinutes[st] = (g.statusMinutes[st] ?? 0) + gapMinutes;

        // Raw break/meeting/dial categorization (Bio Break, Lunch, Tea, Prayer, Meeting, Manual Dial…)
        const cat = breakCategory(a.statusRaw || '', st);
        if (cat) g.rawBreakdown[cat] = (g.rawBreakdown[cat] ?? 0) + gapMinutes;

        const online = st !== 'offline' && st !== 'unknown';
        if (online) {
          if (!g.firstLogin) g.firstLogin = prev.captured_at;
          g.lastLogout = curr.captured_at;
        }

        // Idle split: available/idle + does the agent currently hold a case?
        if (st === 'available' || st === 'idle') {
          const assigned = this.pickMetric(a.metrics || {}, [/ASSIGNED/, /OPEN_CASE/, /ACTIVE_CASE/]);
          if (assigned != null && assigned > 0) g.idleWithCase += gapMinutes;
          else g.idleNoCase += gapMinutes;
        }
      }
    }

    let saved = 0;
    for (const [agentId, g] of Object.entries(acc)) {
      // Skip rows that never resolved to a real agent name (widget labels, bare IDs)
      if (!g.name || g.name === agentId || isSyntheticName(g.name)) continue;
      const idle  = g.idleNoCase + g.idleWithCase;
      const busy  = g.statusMinutes['busy'] ?? 0;
      const off   = g.statusMinutes['offline'] ?? 0;

      // Daily break total = ALL break types combined (tea + lunch + bio + prayer + other).
      // Meetings/training/manual-dial are tracked separately — NOT part of the break total.
      const BREAK_KEYS = ['tea_break', 'lunch_break', 'bio_break', 'prayer_break', 'other_break'];
      const breakdownTotal = BREAK_KEYS.reduce((s, k) => s + (g.rawBreakdown[k] ?? 0), 0);
      const canonicalBrk   = (g.statusMinutes['break'] ?? 0) + (g.statusMinutes['away'] ?? 0);
      const brk = Math.max(breakdownTotal, canonicalBrk);
      const breakdown = {
        ...Object.fromEntries(Object.entries(g.rawBreakdown).map(([k, v]) => [k, Math.round(v)])),
        total_break: Math.round(brk),
      };

      const aht       = this.toSeconds(this.pickMetric(g.lastMetrics, [/HANDLE_TIME/, /\bAHT\b/, /HANDLING_TIME/]));
      const frt       = this.toSeconds(this.pickMetric(g.lastMetrics, [/FIRST_RESPONSE/, /\bFRT\b/, /RESPONSE_TIME/]));
      const contacts  = this.pickMetric(g.lastMetrics, [/CASE.*HANDLED/, /HANDLED.*CASE/, /CASE_COUNT/, /CASES_RECEIVED/, /MESSAGE_COUNT/, /CONTACT/]);

      // Resolve employee: persisted map first, then email/dual-signal resolver
      let employeeId: string | null = null;
      const mapped = await this.dataSource.query(
        `SELECT employee_id FROM sprinklr_agent_map
         WHERE tenant_id = $1 AND sprinklr_agent_id = $2 AND employee_id IS NOT NULL LIMIT 1`,
        [tenantId, agentId],
      );
      if (mapped?.length) {
        employeeId = mapped[0].employee_id;
      } else if (g.email) {
        employeeId = await this.resolveEmployeeId(tenantId, g.email, g.name);
        if (employeeId) {
          // Persist the resolved link so future lookups are instant
          await this.dataSource.query(
            `UPDATE sprinklr_agent_map SET employee_id = $3, last_seen = NOW()
             WHERE tenant_id = $1 AND sprinklr_agent_id = $2`,
            [tenantId, agentId, employeeId],
          ).catch(() => undefined);
        }
      }

      await this.dataSource.query(
        `INSERT INTO agent_daily_stats
           (tenant_id, stat_date, sprinklr_agent_id, agent_name, agent_email, employee_id,
            first_login, last_logout,
            total_working_minutes, idle_no_case_minutes, idle_with_case_minutes,
            busy_minutes, break_minutes, offline_minutes,
            contacts_received, aht_seconds, avg_response_seconds,
            status_minutes, extra, break_breakdown, computed_at)
         VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19::jsonb,$20::jsonb,NOW())
         ON CONFLICT (tenant_id, stat_date, sprinklr_agent_id) DO UPDATE SET
           agent_name             = EXCLUDED.agent_name,
           agent_email            = COALESCE(EXCLUDED.agent_email, agent_daily_stats.agent_email),
           employee_id            = COALESCE(EXCLUDED.employee_id, agent_daily_stats.employee_id),
           first_login            = EXCLUDED.first_login,
           last_logout            = EXCLUDED.last_logout,
           total_working_minutes  = EXCLUDED.total_working_minutes,
           idle_no_case_minutes   = EXCLUDED.idle_no_case_minutes,
           idle_with_case_minutes = EXCLUDED.idle_with_case_minutes,
           busy_minutes           = EXCLUDED.busy_minutes,
           break_minutes          = EXCLUDED.break_minutes,
           offline_minutes        = EXCLUDED.offline_minutes,
           contacts_received      = COALESCE(EXCLUDED.contacts_received, agent_daily_stats.contacts_received),
           aht_seconds            = COALESCE(EXCLUDED.aht_seconds, agent_daily_stats.aht_seconds),
           avg_response_seconds   = COALESCE(EXCLUDED.avg_response_seconds, agent_daily_stats.avg_response_seconds),
           status_minutes         = EXCLUDED.status_minutes,
           extra                  = EXCLUDED.extra,
           break_breakdown        = EXCLUDED.break_breakdown,
           computed_at            = NOW()`,
        [
          tenantId, date, agentId, g.name, g.email, employeeId,
          g.firstLogin, g.lastLogout,
          Math.round(idle + busy), Math.round(g.idleNoCase), Math.round(g.idleWithCase),
          Math.round(busy), Math.round(brk), Math.round(off),
          contacts, aht, frt,
          JSON.stringify(Object.fromEntries(Object.entries(g.statusMinutes).map(([k, v]) => [k, Math.round(v)]))),
          JSON.stringify(g.lastMetrics),
          JSON.stringify(breakdown),
        ],
      );
      saved++;
    }

    this.logger.log(`[${tenantId}] Daily stats computed for ${date}: ${saved} agents`);
    return { agents: saved };
  }

  // Throttle: auto-recompute today's stats at most once per 5 minutes after ingest
  private lastRollupAt = new Map<string, number>();

  private async maybeRollupToday(tenantId: string): Promise<void> {
    const last = this.lastRollupAt.get(tenantId) ?? 0;
    if (Date.now() - last < 5 * 60_000) return;
    this.lastRollupAt.set(tenantId, Date.now());
    const today = new Date(Date.now() + 3 * 3600e3).toISOString().slice(0, 10); // Kuwait UTC+3
    await this.computeDailyStats(tenantId, today).catch(e =>
      this.logger.warn(`Auto rollup failed: ${e.message}`));
    await this.computeViolations(tenantId, today).catch(e =>
      this.logger.warn(`Violations compute failed: ${e.message}`));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  COMPLIANCE / VIOLATIONS ENGINE
  //  excess_break · late_login · early_logout · off_schedule ·
  //  unauthorized_meeting · unauthorized_manual_dial
  // ═══════════════════════════════════════════════════════════════════════════
  // Defaults — overridable per tenant via settings key 'compliance_config'
  private static readonly COMPLIANCE_DEFAULTS = {
    breakLimitMin:  60,  // daily break allowance (all types combined)
    lateGraceMin:   10,  // grace period for login after shift start
    earlyGraceMin:  10,  // grace period for logout before shift end
    meetingMinFlag: 15,  // meeting minutes before flagging
    dialMinFlag:    5,   // manual-dial minutes before flagging
  };

  async getComplianceConfig(tenantId: string) {
    try {
      const rows = await this.dataSource.query(
        `SELECT setting_value FROM tenant_settings
         WHERE tenant_id = $1 AND setting_key = 'compliance_config' LIMIT 1`,
        [tenantId],
      );
      const v = rows?.[0]?.setting_value;
      const saved = v ? (typeof v === 'object' ? v : JSON.parse(v)) : {};
      return { ...SprinklrService.COMPLIANCE_DEFAULTS, ...saved };
    } catch {
      return { ...SprinklrService.COMPLIANCE_DEFAULTS };
    }
  }

  async saveComplianceConfig(tenantId: string, config: Partial<typeof SprinklrService.COMPLIANCE_DEFAULTS>) {
    // Sanitize: numeric, sane bounds
    const clean: Record<string, number> = {};
    for (const key of Object.keys(SprinklrService.COMPLIANCE_DEFAULTS) as (keyof typeof SprinklrService.COMPLIANCE_DEFAULTS)[]) {
      const v = Number(config[key]);
      if (Number.isFinite(v) && v >= 0 && v <= 480) clean[key] = Math.round(v);
    }
    await this.dataSource.query(
      `INSERT INTO tenant_settings (tenant_id, setting_key, setting_value, setting_group, updated_at)
       VALUES ($1, 'compliance_config', $2::jsonb, 'compliance', NOW())
       ON CONFLICT (tenant_id, setting_key) DO UPDATE SET setting_value = $2::jsonb, updated_at = NOW()`,
      [tenantId, JSON.stringify(clean)],
    );
    return this.getComplianceConfig(tenantId);
  }

  async computeViolations(tenantId: string, date: string): Promise<{ violations: number }> {
    const cfg = await this.getComplianceConfig(tenantId);

    // 1. Daily stats for the date (already linked to employees by email)
    const stats: any[] = await this.dataSource.query(
      `SELECT * FROM agent_daily_stats
       WHERE tenant_id = $1 AND stat_date = $2::date`,
      [tenantId, date],
    );
    if (!stats.length) return { violations: 0 };

    // 2. Scheduled shifts for the date (from attendance/import data)
    const schedules: any[] = await this.dataSource.query(
      `SELECT ar.employee_id, ar.scheduled_start, ar.scheduled_end,
              sc.code AS shift_code, sc.is_working_shift, sc.is_leave_code
       FROM attendance_records ar
       LEFT JOIN shift_codes sc ON sc.id = ar.scheduled_shift_code_id
       WHERE ar.tenant_id = $1 AND ar.attendance_date = $2::date`,
      [tenantId, date],
    );
    const schedByEmp = new Map(schedules.map(s => [s.employee_id, s]));

    // 3. Approved permissions / break requests for the date, per employee
    const perms: any[] = await this.dataSource.query(
      `SELECT r.employee_id, rt.code AS req_type, rp.start_time, rp.end_time
       FROM requests r
       JOIN request_types rt ON rt.id = r.request_type_id
       LEFT JOIN request_permissions rp ON rp.request_id = r.id
       WHERE r.tenant_id = $1 AND r.status = 'approved'
         AND (rp.permission_date = $2::date OR rp.permission_date IS NULL AND r.created_at::date = $2::date)`,
      [tenantId, date],
    );
    const permsByEmp = new Map<string, any[]>();
    perms.forEach(p => {
      if (!p.employee_id) return;
      const arr = permsByEmp.get(p.employee_id) || [];
      arr.push(p);
      permsByEmp.set(p.employee_id, arr);
    });
    const hasApproval = (employeeId: string | null) =>
      !!employeeId && (permsByEmp.get(employeeId)?.length ?? 0) > 0;

    const sev = (mins: number, lo: number, hi: number) =>
      mins >= hi ? 'high' : mins >= lo ? 'medium' : 'low';

    type V = {
      type: string; severity: string; minutes: number | null;
      shiftStart?: string | null; shiftEnd?: string | null; actualAt?: string | null;
      details: Record<string, any>;
    };

    let count = 0;
    for (const s of stats) {
      const breakdown = typeof s.break_breakdown === 'object'
        ? (s.break_breakdown || {}) : JSON.parse(s.break_breakdown || '{}');
      const sched = s.employee_id ? schedByEmp.get(s.employee_id) : null;
      const approved = hasApproval(s.employee_id);
      const violations: V[] = [];

      // ── excess_break: all break types combined > 60 min/day ──
      const totalBreak = +breakdown.total_break || +s.break_minutes || 0;
      if (totalBreak > cfg.breakLimitMin) {
        const excess = totalBreak - cfg.breakLimitMin;
        violations.push({
          type: 'excess_break',
          severity: sev(excess, 15, 45),
          minutes: excess,
          details: {
            totalBreakMinutes: totalBreak, limitMinutes: cfg.breakLimitMin,
            breakdown: {
              tea:    breakdown.tea_break    ?? 0, lunch: breakdown.lunch_break ?? 0,
              bio:    breakdown.bio_break    ?? 0, prayer: breakdown.prayer_break ?? 0,
              other:  breakdown.other_break  ?? 0,
            },
          },
        });
      }

      // ── late_login: first Sprinklr activity after scheduled shift start ──
      if (sched?.scheduled_start && s.first_login && !approved) {
        const lateMin = Math.round(
          (new Date(s.first_login).getTime() - new Date(sched.scheduled_start).getTime()) / 60000);
        if (lateMin > cfg.lateGraceMin) {
          violations.push({
            type: 'late_login',
            severity: sev(lateMin, 30, 60),
            minutes: lateMin,
            shiftStart: sched.scheduled_start, actualAt: s.first_login,
            details: { shiftCode: sched.shift_code, graceMinutes: cfg.lateGraceMin },
          });
        }
      }

      // ── early_logout: last Sprinklr activity before scheduled shift end ──
      if (sched?.scheduled_end && s.last_logout && !approved) {
        const earlyMin = Math.round(
          (new Date(sched.scheduled_end).getTime() - new Date(s.last_logout).getTime()) / 60000);
        if (earlyMin > cfg.earlyGraceMin) {
          violations.push({
            type: 'early_logout',
            severity: sev(earlyMin, 30, 60),
            minutes: earlyMin,
            shiftEnd: sched.scheduled_end, actualAt: s.last_logout,
            details: { shiftCode: sched.shift_code, graceMinutes: cfg.earlyGraceMin },
          });
        }
      }

      // ── off_schedule: active on Sprinklr but no working shift scheduled ──
      if (s.employee_id && s.total_working_minutes > 30) {
        const noShift   = !sched;
        const leaveDay  = sched && (sched.is_leave_code || sched.is_working_shift === false);
        if (noShift || leaveDay) {
          violations.push({
            type: 'off_schedule',
            severity: 'medium',
            minutes: s.total_working_minutes,
            details: {
              reason: noShift ? 'no_scheduled_shift' : 'scheduled_off_or_leave',
              shiftCode: sched?.shift_code ?? null,
              workedMinutes: s.total_working_minutes,
            },
          });
        }
      }

      // ── unauthorized_meeting: meeting status without an approved request ──
      const meetingMin = (+breakdown.meeting || 0) + (+breakdown.training || 0);
      if (meetingMin >= cfg.meetingMinFlag && !approved) {
        violations.push({
          type: 'unauthorized_meeting',
          severity: sev(meetingMin, 30, 60),
          minutes: Math.round(meetingMin),
          details: { meetingMinutes: Math.round(+breakdown.meeting || 0), trainingMinutes: Math.round(+breakdown.training || 0) },
        });
      }

      // ── unauthorized_manual_dial: manual/outbound dial without approval ──
      const dialMin = +breakdown.manual_dial || 0;
      if (dialMin >= cfg.dialMinFlag && !approved) {
        violations.push({
          type: 'unauthorized_manual_dial',
          severity: sev(dialMin, 20, 45),
          minutes: Math.round(dialMin),
          details: { manualDialMinutes: Math.round(dialMin) },
        });
      }

      // Upsert all violations for this agent/date
      for (const v of violations) {
        await this.dataSource.query(
          `INSERT INTO agent_violations
             (tenant_id, violation_date, sprinklr_agent_id, agent_name, agent_email, employee_id,
              violation_type, severity, minutes, shift_start, shift_end, actual_at, details)
           VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,$8,$9,$10,$11,$12,$13::jsonb)
           ON CONFLICT (tenant_id, violation_date, sprinklr_agent_id, violation_type) DO UPDATE SET
             agent_name  = EXCLUDED.agent_name,
             agent_email = COALESCE(EXCLUDED.agent_email, agent_violations.agent_email),
             employee_id = COALESCE(EXCLUDED.employee_id, agent_violations.employee_id),
             severity    = EXCLUDED.severity,
             minutes     = EXCLUDED.minutes,
             shift_start = EXCLUDED.shift_start,
             shift_end   = EXCLUDED.shift_end,
             actual_at   = EXCLUDED.actual_at,
             details     = EXCLUDED.details`,
          [
            tenantId, date, s.sprinklr_agent_id, s.agent_name, s.agent_email || '', s.employee_id,
            v.type, v.severity, v.minutes,
            v.shiftStart ?? null, v.shiftEnd ?? null, v.actualAt ?? null,
            JSON.stringify(v.details),
          ],
        );
        count++;
      }
    }

    this.logger.log(`[${tenantId}] Violations computed for ${date}: ${count}`);
    return { violations: count };
  }

  // ── Violations report ───────────────────────────────────────────────────────
  async getViolationsReport(tenantId: string, from: string, to: string) {
    const rows = await this.dataSource.query(
      `SELECT v.*, e.employee_no,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name
       FROM agent_violations v
       LEFT JOIN employees e ON e.id = v.employee_id
       WHERE v.tenant_id = $1 AND v.violation_date BETWEEN $2::date AND $3::date
       ORDER BY v.violation_date DESC, v.severity DESC, v.minutes DESC NULLS LAST`,
      [tenantId, from, to],
    );

    const byType: Record<string, number> = {};
    const bySeverity: Record<string, number> = {};
    let openCount = 0;
    for (const r of rows) {
      byType[r.violation_type]  = (byType[r.violation_type]  ?? 0) + 1;
      bySeverity[r.severity]    = (bySeverity[r.severity]    ?? 0) + 1;
      if (r.status === 'open') openCount++;
    }

    // Repeat offenders (most violations in range)
    const topOffenders = Object.values(
      rows.reduce((m: Record<string, any>, r: any) => {
        const k = r.sprinklr_agent_id;
        m[k] = m[k] || { agentId: k, name: r.employee_name || r.agent_name, count: 0, totalMinutes: 0 };
        m[k].count++;
        m[k].totalMinutes += +r.minutes || 0;
        return m;
      }, {}),
    ).sort((a: any, b: any) => b.count - a.count).slice(0, 10);

    return { from, to, summary: { total: rows.length, open: openCount, byType, bySeverity }, topOffenders, rows };
  }

  async setViolationStatus(tenantId: string, id: string, status: string, reviewerId: string) {
    if (!['open', 'reviewed', 'justified'].includes(status)) status = 'reviewed';
    await this.dataSource.query(
      `UPDATE agent_violations
       SET status = $3, reviewed_by = $4, reviewed_at = NOW()
       WHERE tenant_id = $1 AND id = $2`,
      [tenantId, id, status, reviewerId],
    );
    return { ok: true };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  DAILY REPORT — per agent per day, joined with system employee via email
  // ═══════════════════════════════════════════════════════════════════════════
  async getAgentDailyReport(tenantId: string, from: string, to: string, refresh = false) {
    if (refresh) {
      // Recompute every day in range (bounded to 31 days)
      const start = new Date(from); const end = new Date(to);
      for (let d = new Date(start), i = 0; d <= end && i < 31; d.setDate(d.getDate() + 1), i++) {
        const ds = d.toISOString().slice(0, 10);
        await this.computeDailyStats(tenantId, ds);
        await this.computeViolations(tenantId, ds).catch(() => undefined);
      }
    }

    const rows = await this.dataSource.query(
      `SELECT s.stat_date, s.sprinklr_agent_id, s.agent_name, s.agent_email,
              s.employee_id,
              e.employee_no,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name,
              s.first_login, s.last_logout,
              s.total_working_minutes, s.idle_no_case_minutes, s.idle_with_case_minutes,
              s.busy_minutes, s.break_minutes, s.offline_minutes,
              s.contacts_received, s.aht_seconds, s.avg_response_seconds,
              s.status_minutes, s.extra, s.break_breakdown
       FROM agent_daily_stats s
       LEFT JOIN employees e ON e.id = s.employee_id
       WHERE s.tenant_id = $1 AND s.stat_date BETWEEN $2::date AND $3::date
       ORDER BY s.stat_date DESC, s.total_working_minutes DESC`,
      [tenantId, from, to],
    );

    // Per-day totals for the summary strip
    const byDate: Record<string, { agents: number; workingMinutes: number; contacts: number }> = {};
    for (const r of rows) {
      const d = String(r.stat_date).slice(0, 10);
      byDate[d] = byDate[d] || { agents: 0, workingMinutes: 0, contacts: 0 };
      byDate[d].agents++;
      byDate[d].workingMinutes += +r.total_working_minutes || 0;
      byDate[d].contacts       += +r.contacts_received     || 0;
    }

    return { from, to, days: byDate, rows };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  CONTACT FORECAST — weekday-seasonal moving average over daily history
  // ═══════════════════════════════════════════════════════════════════════════
  async getContactForecast(tenantId: string, daysAhead = 7) {
    const history: { stat_date: string; contacts: string; agents: string; working: string }[] =
      await this.dataSource.query(
        `SELECT stat_date,
                COALESCE(SUM(contacts_received), 0)     AS contacts,
                COUNT(*)                                AS agents,
                COALESCE(SUM(total_working_minutes), 0) AS working
         FROM agent_daily_stats
         WHERE tenant_id = $1 AND stat_date >= CURRENT_DATE - INTERVAL '28 days'
         GROUP BY stat_date ORDER BY stat_date ASC`,
        [tenantId],
      );

    const hist = history.map(h => ({
      date:     String(h.stat_date).slice(0, 10),
      contacts: +h.contacts,
      agents:   +h.agents,
      workingMinutes: +h.working,
    }));

    const withData = hist.filter(h => h.contacts > 0);
    const overallAvg = withData.length
      ? withData.reduce((s, h) => s + h.contacts, 0) / withData.length : 0;

    // Weekday means (0=Sun..6=Sat)
    const weekday: Record<number, number[]> = {};
    withData.forEach(h => {
      const wd = new Date(h.date).getDay();
      (weekday[wd] = weekday[wd] || []).push(h.contacts);
    });

    const forecast: { date: string; predictedContacts: number; method: string }[] = [];
    for (let i = 1; i <= daysAhead; i++) {
      const d  = new Date(Date.now() + 3 * 3600e3 + i * 86400e3);
      const ds = d.toISOString().slice(0, 10);
      const wd = d.getDay();
      const wdVals = weekday[wd];
      const predicted = wdVals?.length
        ? wdVals.reduce((s, v) => s + v, 0) / wdVals.length
        : overallAvg;
      forecast.push({
        date: ds,
        predictedContacts: Math.round(predicted),
        method: wdVals?.length ? `weekday-avg(${wdVals.length})` : 'overall-avg',
      });
    }

    return {
      history: hist,
      forecast,
      confidence: withData.length >= 14 ? 'medium' : (withData.length >= 7 ? 'low' : 'insufficient-data'),
      note: withData.length < 7
        ? 'Need at least 7 days of contact data for a meaningful forecast. Forecast will improve as daily data accumulates.'
        : null,
    };
  }
}
