import { Injectable, Logger } from '@nestjs/common';
import { DataSource } from 'typeorm';
import { SprinklrSnapshot, SprinklrApiConfig, SprinklrAgent } from './sprinklr.types';

// Names generated by DOM-scraping fallback or Sprinklr widget labels —
// must never be stored as real agent names.
const SYNTHETIC_NAME_PATTERNS = [
  /^(available|unavailable|busy|idle|break|away|offline|unknown)\s*\d*$/i,
  /^agent\s+status/i,
  /^(bio\s*break|prayer(\s*break)?|lunch(\s*break)?|short\s*break|meeting|training|coaching|wrap\s*up)(\s+\d+)?$/i,
  /^(no\s+data|user\s+current\s+status|current\s+status|n\/?a|null|undefined|total|grand\s+total|all\s+agents?|active\s+queue)/i,
];

function isSyntheticName(name: string): boolean {
  if (!name) return true;
  const t = name.trim();
  return SYNTHETIC_NAME_PATTERNS.some(re => re.test(t));
}

// IDs generated by the DOM-scraping fallback ("available_0", "offline_3") — not real agents
function isSyntheticAgent(agent: { agentId?: string; agentName?: string }): boolean {
  const id = agent.agentId || '';
  if (/^(available|unavailable|busy|idle|break|away|offline|unknown)_\d+$/i.test(id)) return true;
  return !!agent.agentName && isSyntheticName(agent.agentName) && !id.match(/^\d/);
}

@Injectable()
export class SprinklrService {
  private readonly logger = new Logger(SprinklrService.name);

  // In-memory cache per tenant: tenantId → latest snapshot
  private readonly snapshotCache = new Map<string, SprinklrSnapshot & { receivedAt: number }>();

  constructor(private readonly dataSource: DataSource) {}

  // ── Receive snapshot from Chrome Extension (or internal poller) ────────────
  async ingestSnapshot(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    const enriched = { ...snapshot, receivedAt: Date.now() };
    this.snapshotCache.set(tenantId, enriched);

    // Persist to DB for history + RTA integration
    await this.persistSnapshot(tenantId, snapshot);

    // Update headcount_intervals with live Sprinklr data
    await this.updateLiveCoverage(tenantId, snapshot);

    // Keep sprinklr_agent_map fresh (email → users → employees lookup)
    await this.upsertAgentMap(tenantId, snapshot.agents || []).catch(() => undefined);

    // Recompute today's daily stats (throttled to once per 5 min)
    void this.maybeRollupToday(tenantId);

    this.logger.log(
      `[${tenantId}] Sprinklr snapshot ingested: ${snapshot.queues.length} queues, ${snapshot.agents.length} agents`,
    );
  }

  // ── Get latest cached snapshot (memory first, DB fallback after restart) ───
  async getLatestSnapshot(tenantId: string) {
    let snap = this.snapshotCache.get(tenantId);

    // Memory cache empty (e.g. backend restarted) → hydrate from DB
    if (!snap) {
      try {
        const rows = await this.dataSource.query(
          `SELECT captured_at, queues_json, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
           ORDER BY captured_at DESC LIMIT 1`,
          [tenantId],
        );
        if (rows?.length) {
          const r = rows[0];
          const parse = (v: any) => (Array.isArray(v) ? v : JSON.parse(v || '[]'));
          snap = {
            source:     'sprinklr',
            capturedAt: r.captured_at,
            queues:     parse(r.queues_json),
            agents:     parse(r.agents_json),
            receivedAt: new Date(r.captured_at).getTime(),
          };
          this.snapshotCache.set(tenantId, snap);
          this.logger.log(`[${tenantId}] Snapshot cache hydrated from DB (captured ${r.captured_at})`);
        }
      } catch (e: any) {
        this.logger.warn(`[${tenantId}] DB snapshot hydration failed: ${e.message}`);
      }
    }

    if (!snap) return null;
    return {
      ...snap,
      staleSec: Math.round((Date.now() - snap.receivedAt) / 1000),
      isStale: Date.now() - snap.receivedAt > 120_000, // > 2 min
    };
  }

  // ── Get queue summary for RTA dashboard ───────────────────────────────────
  async getQueueSummary(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    if (!snap) {
      return {
        capturedAt: null,
        staleSec: 0,
        isStale: true,
        summary: { totalWaiting: 0, totalInProgress: 0, totalAvailable: 0, totalBusy: 0, avgSla: 100 },
        atRisk: [],
        queues: [],
        agents: [],
      };
    }

    // Filter out DOM-scraping artefacts (date-range text picked up as queue name)
    const rawQueues = snap.queues.filter(q =>
      q.queueName &&
      !/^Selected date/i.test(q.queueName) &&
      !/^\d{2}\/\d{2}\/\d{4}/.test(q.queueName) &&
      q.queueName.length < 100,
    );

    // Build per-queue agent counts from agent-level statuses as fallback when
    // queue-level agentsAvailable / agentsBusy are not populated (0).
    const agentsByQueue: Record<string, { avail: number; busy: number }> = {};
    for (const a of snap.agents) {
      const qid = a.queueId;
      if (!qid) continue;
      if (!agentsByQueue[qid]) agentsByQueue[qid] = { avail: 0, busy: 0 };
      if (a.status === 'available' || a.status === 'idle') agentsByQueue[qid].avail++;
      if (a.status === 'busy' || a.status === 'away') agentsByQueue[qid].busy++;
    }

    const queues = rawQueues.map(q => ({
      ...q,
      agentsAvailable: q.agentsAvailable || agentsByQueue[q.queueId]?.avail || 0,
      agentsBusy:      q.agentsBusy      || agentsByQueue[q.queueId]?.busy || 0,
    }));

    // Count unique agents by status — avoids double-counting agents who appear in
    // multiple queues (e.g. the same person handles both WhatsApp and Live Chat).
    // Agent-level count is always preferred over queue-level sums for the summary.
    const allAvailAgents = snap.agents.filter(a => a.status === 'available' || a.status === 'idle').length;
    const allBusyAgents  = snap.agents.filter(a => a.status === 'busy' || a.status === 'away').length;
    const totalAvailableFromQueues = queues.reduce((s, q) => s + q.agentsAvailable, 0);
    const totalBusyFromQueues      = queues.reduce((s, q) => s + q.agentsBusy, 0);

    const totalWaiting   = queues.reduce((s, q) => s + q.waiting, 0);
    const totalInProgress= queues.reduce((s, q) => s + q.inProgress, 0);
    // Agent-level counts are deduplicated (each person once).
    // Fall back to queue-sums only when the agents array is empty.
    const totalAvailable = allAvailAgents || totalAvailableFromQueues;
    const totalBusy      = allBusyAgents  || totalBusyFromQueues;
    const avgSla         = queues.length
      ? queues.reduce((s, q) => s + (q.slaPct ?? 100), 0) / queues.length
      : 100;

    const atRisk = queues.filter(q => (q.slaPct ?? 100) < 80);

    return {
      capturedAt: snap.capturedAt,
      staleSec:   snap.staleSec,
      isStale:    snap.isStale,
      summary: { totalWaiting, totalInProgress, totalAvailable, totalBusy, avgSla: +avgSla.toFixed(1) },
      atRisk,
      queues,
      agents:  snap.agents,
    };
  }

  // ── Direct Sprinklr API poller (used when API key is available) ────────────
  async pollFromApi(tenantId: string): Promise<void> {
    const config = await this.getApiConfig(tenantId);
    if (!config?.apiKey) {
      this.logger.warn(`[${tenantId}] No Sprinklr API key configured`);
      return;
    }

    try {
      const snapshot = await this.fetchFromSprinklrApi(config);
      await this.ingestSnapshot(tenantId, snapshot);
    } catch (e: any) {
      this.logger.error(`[${tenantId}] Sprinklr API poll failed: ${e.message}`);
    }
  }

  // ── Sprinklr REST API calls ────────────────────────────────────────────────
  private async fetchFromSprinklrApi(config: SprinklrApiConfig): Promise<SprinklrSnapshot> {
    const headers = {
      'key':          config.apiKey,
      'X-PARTNER-ID': config.partnerId,
      'Content-Type': 'application/json',
    };

    // Sprinklr API v2 endpoints for queue monitoring
    const [queuesRes, agentsRes] = await Promise.allSettled([
      fetch(`${config.baseUrl}/api/v2/${config.environmentId}/listening/stream`, { headers }),
      fetch(`${config.baseUrl}/api/v2/${config.environmentId}/monitoring/agent-status`, { headers }),
    ]);

    const queues = queuesRes.status === 'fulfilled' && queuesRes.value.ok
      ? await queuesRes.value.json().then(d => this.mapSprinklrQueues(d)).catch(() => [])
      : [];

    const agents = agentsRes.status === 'fulfilled' && agentsRes.value.ok
      ? await agentsRes.value.json().then(d => this.mapSprinklrAgents(d)).catch(() => [])
      : [];

    return {
      source: 'api',
      capturedAt: new Date().toISOString(),
      queues,
      agents,
    };
  }

  private mapSprinklrQueues(raw: any): SprinklrSnapshot['queues'] {
    const list = Array.isArray(raw) ? raw : (raw?.data ?? raw?.results ?? raw?.queues ?? []);
    return list.map((q: any) => ({
      queueId:         q.id          || q.channelId   || q.streamId   || '',
      queueName:       q.name        || q.label        || q.title      || '',
      channel:         this.mapChannel(q.channelType   || q.type       || ''),
      waiting:         q.waitingCount|| q.inQueue      || 0,
      inProgress:      q.activeCount || q.engaged      || 0,
      backlog:         q.totalOpen   || 0,
      avgWaitSeconds:  q.avgWaitTime || 0,
      slaBreached:     q.slaBreached || 0,
      slaPct:          q.slaCompliance ?? q.slaPct ?? 100,
      agentsAvailable: q.availableAgents ?? 0,
      agentsBusy:      q.busyAgents ?? 0,
      agentsBreak:     q.breakAgents ?? 0,
      aht:             q.aht ?? 0,
    }));
  }

  private mapSprinklrAgents(raw: any): SprinklrSnapshot['agents'] {
    const list = Array.isArray(raw) ? raw : (raw?.data ?? raw?.users ?? raw?.agents ?? []);
    return list.map((a: any) => ({
      agentId:        a.userId      || a.agentId     || a.id     || '',
      agentName:      a.userName    || a.displayName || a.name   || '',
      status:         this.mapAgentStatus(a.status   || a.availability || ''),
      currentChannel: this.mapChannel(a.channelType || ''),
      queueId:        a.queueId    || a.channelId   || '',
      loginTime:      a.loginTime  || '',
    }));
  }

  private mapChannel(raw: string): SprinklrSnapshot['queues'][0]['channel'] {
    const s = (raw || '').toLowerCase();
    if (s.includes('whatsapp') || s.includes('wa')) return 'whatsapp';
    if (s.includes('chat'))    return 'chat';
    if (s.includes('email'))   return 'email';
    if (s.includes('social') || s.includes('twitter') || s.includes('instagram')) return 'social';
    if (s.includes('voice') || s.includes('call'))  return 'voice';
    return 'unknown';
  }

  private mapAgentStatus(raw: string): SprinklrSnapshot['agents'][0]['status'] {
    const s = (raw || '').toLowerCase();
    if (s.includes('available') || s.includes('online') || s.includes('idle') || s.includes('ready') || s.includes('logged in') || s.includes('loggedin')) return 'available';
    if (s.includes('busy') || s.includes('engaged') || s.includes('handling') || s.includes('active')) return 'busy';
    if (s.includes('break') || s.includes('bio') || s.includes('lunch') || s.includes('prayer') || s.includes('tea')) return 'break';
    if (s.includes('away') || s.includes('wrap') || s.includes('acw')) return 'away';
    if (s.includes('offline') || s.includes('logged out') || s.includes('loggedout')) return 'offline';
    return 'unknown';
  }

  // ── Persist snapshot to DB (integration_snapshots table) ──────────────────
  private async persistSnapshot(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    try {
      await this.dataSource.query(
        `INSERT INTO integration_snapshots
           (tenant_id, source, captured_at, queues_json, agents_json, queue_count, agent_count)
         VALUES ($1, 'sprinklr', $2::timestamptz, $3::jsonb, $4::jsonb, $5, $6)`,
        [
          tenantId,
          snapshot.capturedAt,
          JSON.stringify(snapshot.queues),
          JSON.stringify(snapshot.agents),
          snapshot.queues.length,
          snapshot.agents.length,
        ],
      );
    } catch {
      // Table may not exist yet — non-fatal
    }
  }

  // ── Update headcount_intervals with live agent counts from Sprinklr ────────
  private async updateLiveCoverage(tenantId: string, snapshot: SprinklrSnapshot): Promise<void> {
    const now = new Date();
    const hh  = String(now.getHours()).padStart(2, '0');
    const mm  = Math.floor(now.getMinutes() / 15) * 15;
    const intervalStart = `${hh}:${String(mm).padStart(2, '0')}`;

    const totalAvailable = snapshot.agents.filter(a => a.status === 'available').length;
    const totalBusy      = snapshot.agents.filter(a => a.status === 'busy').length;
    const liveHc         = totalAvailable + totalBusy;

    if (liveHc === 0) return;

    try {
      await this.dataSource.query(
        `UPDATE headcount_intervals
         SET live_hc = $1, live_updated_at = NOW()
         WHERE tenant_id = $2
           AND snapshot_date = CURRENT_DATE
           AND interval_start = $3::time`,
        [liveHc, tenantId, intervalStart],
      );
    } catch {
      // headcount_intervals may not have live_hc column yet — non-fatal
    }
  }

  // ── Config management ──────────────────────────────────────────────────────
  async getApiConfig(tenantId: string): Promise<SprinklrApiConfig | null> {
    try {
      const [row] = await this.dataSource.query(
        `SELECT setting_value FROM tenant_settings
         WHERE tenant_id = $1 AND setting_key = 'sprinklr_api_config'`,
        [tenantId],
      );
      if (!row) return null;
      const v = row.setting_value;
      return typeof v === 'object' ? v : JSON.parse(v);
    } catch {
      return null;
    }
  }

  async saveApiConfig(tenantId: string, config: SprinklrApiConfig): Promise<void> {
    await this.dataSource.query(
      `INSERT INTO tenant_settings (tenant_id, setting_key, setting_value, setting_group, updated_at)
       VALUES ($1, 'sprinklr_api_config', $2::jsonb, 'integrations', NOW())
       ON CONFLICT (tenant_id, setting_key) DO UPDATE SET setting_value = $2::jsonb, updated_at = NOW()`,
      [tenantId, JSON.stringify(config)],
    );
  }

  // ── Historical snapshots ───────────────────────────────────────────────────
  async getHistory(tenantId: string, hours = 24) {
    try {
      return this.dataSource.query(
        `SELECT id, source, captured_at, queue_count, agent_count
         FROM integration_snapshots
         WHERE tenant_id = $1 AND source = 'sprinklr'
           AND captured_at >= NOW() - ($2 || ' hours')::interval
         ORDER BY captured_at DESC
         LIMIT 200`,
        [tenantId, hours],
      );
    } catch {
      return [];
    }
  }

  // ── Break Tracker — full live dashboard ─────────────────────────────────────
  // Who is on break NOW (name, function, raw label, started at, minutes so far),
  // who is available, per-agent break history, and authorization via BOTH the
  // permission requests AND the Break Management module (break_requests).
  async getBreakTracker(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    const agents = (snap?.agents ?? []).filter(a => !isSyntheticAgent(a as any) && a.agentName);

    const [agentHistory, activePermissions, empMap, activeBreakReqs] = await Promise.all([
      this.computeBreakHistory(tenantId, 12),
      this.getActivePermissions(tenantId),
      // sprinklr agent → employee + function
      this.dataSource.query(
        `SELECT m.sprinklr_agent_id, m.employee_id, e.employee_no,
                TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name,
                f.name AS function_name
         FROM sprinklr_agent_map m
         JOIN employees e ON e.id = m.employee_id
         LEFT JOIN functions f ON f.id = e.function_id
         WHERE m.tenant_id = $1 AND m.employee_id IS NOT NULL`,
        [tenantId],
      ).catch(() => []),
      // Break Management: approved break requests covering RIGHT NOW
      this.dataSource.query(
        `SELECT employee_id FROM break_requests
         WHERE tenant_id = $1 AND status = 'approved'
           AND schedule_date  =  (NOW() AT TIME ZONE 'Asia/Kuwait')::date
           AND requested_start <= (NOW() AT TIME ZONE 'Asia/Kuwait')::time
           AND requested_end   >= (NOW() AT TIME ZONE 'Asia/Kuwait')::time`,
        [tenantId],
      ).catch(() => []),
    ]);

    const empByAgent = new Map<string, any>(empMap.map((m: any) => [m.sprinklr_agent_id, m]));
    const permEmpIds  = new Set(activePermissions.map((p: any) => p.employee_id).filter(Boolean));
    const breakEmpIds = new Set(activeBreakReqs.map((b: any) => b.employee_id));

    const decorate = (a: any) => {
      const emp  = empByAgent.get(a.agentId);
      const hist = agentHistory.find(h => h.agentId === a.agentId);
      return {
        agentId:        a.agentId,
        agentName:      a.agentName,
        employeeName:   emp?.employee_name ?? null,
        employeeNo:     emp?.employee_no ?? null,
        functionName:   emp?.function_name ?? null,
        status:         a.status,
        statusRaw:      a.statusRaw || '',
        breakCount:        hist?.breakCount ?? 0,
        totalBreakMinutes: hist?.totalBreakMinutes ?? 0,
        lastBreakStart:    hist?.lastBreakStart ?? null,
        breaks:            hist?.breaks ?? [],
      };
    };

    // On break now — with start time + running duration + authorization source
    const onBreakNow = agents
      .filter(a => a.status === 'break' || a.status === 'away')
      .map(a => {
        const d = decorate(a);
        const emp = empByAgent.get(a.agentId);
        const viaBreakMgmt  = !!emp && breakEmpIds.has(emp.employee_id);
        const viaPermission = !!emp && permEmpIds.has(emp.employee_id);
        const startedAt = d.lastBreakStart;
        return {
          ...d,
          currentlyBreaking: true,
          breakStartedAt: startedAt,
          minutesSoFar: startedAt ? Math.max(0, Math.round((Date.now() - new Date(startedAt).getTime()) / 60000)) : null,
          isAuthorized: viaBreakMgmt || viaPermission,
          authSource:   viaBreakMgmt ? 'break_management' : viaPermission ? 'permission' : null,
        };
      })
      .sort((x, y) => (y.minutesSoFar ?? 0) - (x.minutesSoFar ?? 0));

    // Available / busy right now — names + functions for the live board
    const availableNow = agents
      .filter(a => a.status === 'available' || a.status === 'idle')
      .map(decorate)
      .sort((x, y) => (x.employeeName || x.agentName).localeCompare(y.employeeName || y.agentName));
    const busyNow = agents.filter(a => a.status === 'busy').map(decorate);

    return {
      capturedAt: snap?.capturedAt ?? null,
      isStale:    snap?.isStale ?? true,
      onBreakNow,
      availableNow,
      busyNow,
      unauthorizedCount: onBreakNow.filter(a => !a.isAuthorized).length,
      authorizedCount:   onBreakNow.filter(a => a.isAuthorized).length,
      breakMgmtActiveRequests: activeBreakReqs.length,
      agentHistory,
      activePermissions,
    };
  }

  private async computeBreakHistory(tenantId: string, hours: number) {
    try {
      // Latest first then reverse — ASC+LIMIT would drop today's data when busy
      const snapshots: { captured_at: string; agents_json: any }[] =
        (await this.dataSource.query(
          `SELECT captured_at, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
             AND captured_at >= NOW() - ($2 || ' hours')::interval
           ORDER BY captured_at DESC
           LIMIT 2000`,
          [tenantId, hours],
        )).reverse();

      if (!snapshots.length) return [];

      const agentTimeline: Record<string, {
        name: string;
        breakCount: number;
        totalBreakMinutes: number;
        lastBreakStart: string | null;
        currentlyBreaking: boolean;
        breaks: { start: string; end: string; minutes: number }[];
        loginTime: string | null;
      }> = {};
      const prevStatus: Record<string, string> = {};

      for (const snap of snapshots) {
        const agents: any[] = Array.isArray(snap.agents_json)
          ? snap.agents_json
          : JSON.parse(snap.agents_json || '[]');
        const ts = snap.captured_at;

        for (const agent of agents) {
          if (!agent.agentId) continue;
          if (isSyntheticAgent(agent)) continue; // skip DOM-scrape placeholder rows
          if (!agentTimeline[agent.agentId]) {
            const initName = (agent.agentName && !isSyntheticName(agent.agentName)) ? agent.agentName : agent.agentId;
            agentTimeline[agent.agentId] = {
              name: initName,
              breakCount: 0,
              totalBreakMinutes: 0,
              lastBreakStart: null,
              currentlyBreaking: false,
              breaks: [],
              loginTime: agent.loginTime || null,
            };
          } else if (agent.agentName && !isSyntheticName(agent.agentName)) {
            // Update name if we now have a real one
            agentTimeline[agent.agentId].name = agent.agentName;
          }
          const prev = prevStatus[agent.agentId];
          const curr = agent.status || 'unknown';
          const timeline = agentTimeline[agent.agentId];
          const isBreak = curr === 'break' || curr === 'away';
          const wasBreak = prev === 'break' || prev === 'away';

          if (isBreak && !wasBreak) {
            timeline.breakCount++;
            timeline.lastBreakStart = ts;
            timeline.currentlyBreaking = true;
          } else if (!isBreak && wasBreak && timeline.lastBreakStart) {
            const start = new Date(timeline.lastBreakStart);
            const end   = new Date(ts);
            const mins  = Math.max(0, Math.round((end.getTime() - start.getTime()) / 60000));
            timeline.breaks.push({ start: timeline.lastBreakStart, end: ts, minutes: mins });
            timeline.totalBreakMinutes += mins;
            timeline.currentlyBreaking = false;
            // keep lastBreakStart — the history table shows when the LAST break was
          }
          prevStatus[agent.agentId] = curr;
        }
      }

      return Object.entries(agentTimeline).map(([agentId, data]) => ({ agentId, ...data }));
    } catch {
      return [];
    }
  }

  // ── Active Permissions ─────────────────────────────────────────────────────
  // Real schema: request_permissions (permission_date DATE + start/end TIME),
  // employees has first/last name columns — NOT full_name.
  async getActivePermissions(tenantId: string) {
    try {
      return await this.dataSource.query(
        `SELECT r.id, r.employee_id,
                TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name,
                e.employee_no,
                (rp.permission_date::text || ' ' || rp.start_time::text || '+03')::timestamptz AS starts_at,
                (rp.permission_date::text || ' ' || rp.end_time::text   || '+03')::timestamptz AS ends_at,
                rp.reason, r.status,
                f.name AS function_name
         FROM requests r
         JOIN request_permissions rp ON rp.request_id = r.id
         JOIN employees e ON e.id = r.employee_id
         LEFT JOIN functions f ON f.id = e.function_id
         WHERE r.tenant_id = $1
           AND r.status = 'approved'
           AND rp.permission_date = (NOW() AT TIME ZONE 'Asia/Kuwait')::date
           AND rp.start_time <= (NOW() AT TIME ZONE 'Asia/Kuwait')::time
           AND rp.end_time   >= (NOW() AT TIME ZONE 'Asia/Kuwait')::time
         ORDER BY rp.start_time`,
        [tenantId],
      );
    } catch (e: any) {
      this.logger.warn(`getActivePermissions failed: ${e.message}`);
      return [];
    }
  }

  // ── Queue Detail ───────────────────────────────────────────────────────────
  async getQueueDetail(tenantId: string, queueId: string) {
    const snap = await this.getLatestSnapshot(tenantId);
    if (!snap) return null;

    const queue = snap.queues.find(q => q.queueId === queueId);
    if (!queue) return null;

    const queueAgents = snap.agents.filter(a => a.queueId === queueId);
    const allAgents   = snap.agents;

    // Overflow: available agents NOT in this queue
    const overflow = allAgents
      .filter(a => a.status === 'available' && a.queueId !== queueId)
      .slice(0, 10);

    return {
      queue,
      agents: queueAgents,
      overflow,
      capturedAt: snap.capturedAt,
      staleSec: snap.staleSec,
    };
  }

  // ── Coverage Comparison (Schedule vs Live) ────────────────────────────────
  async getCoverageComparison(tenantId: string) {
    const snap = await this.getLatestSnapshot(tenantId);

    const liveSprinklr = snap ? {
      available:    snap.agents.filter(a => a.status === 'available').length,
      busy:         snap.agents.filter(a => a.status === 'busy').length,
      onBreak:      snap.agents.filter(a => a.status === 'break' || a.status === 'away').length,
      offline:      snap.agents.filter(a => a.status === 'offline' || a.status === 'unknown').length,
      totalLoggedIn: snap.agents.filter(a => a.status !== 'offline' && a.status !== 'unknown').length,
    } : null;

    const [intervals, attendance, activePermCount] = await Promise.all([
      this.dataSource.query(
        `SELECT interval_start::text, function_id,
                COALESCE(required_hc, 0) AS required_hc,
                COALESCE(scheduled_hc, 0) AS scheduled_hc,
                COALESCE(live_hc, 0) AS live_hc
         FROM headcount_intervals
         WHERE tenant_id = $1 AND snapshot_date = CURRENT_DATE
         ORDER BY interval_start`,
        [tenantId],
      ).catch(() => []),

      this.dataSource.query(
        `SELECT
           COUNT(*) FILTER (WHERE punch_in IS NOT NULL) AS punched_in,
           COUNT(*) AS total_scheduled
         FROM attendance_records
         WHERE tenant_id = $1 AND attendance_date = CURRENT_DATE`,
        [tenantId],
      ).catch(() => [{}]),

      this.dataSource.query(
        `SELECT COUNT(*) AS cnt
         FROM requests r
         JOIN request_permissions rp ON rp.request_id = r.id
         WHERE r.tenant_id = $1 AND r.status = 'approved'
           AND rp.permission_date = (NOW() AT TIME ZONE 'Asia/Kuwait')::date
           AND rp.start_time <= (NOW() AT TIME ZONE 'Asia/Kuwait')::time
           AND rp.end_time   >= (NOW() AT TIME ZONE 'Asia/Kuwait')::time`,
        [tenantId],
      ).catch(() => [{ cnt: 0 }]),
    ]);

    return {
      intervals,
      attendance: attendance[0] ?? { punched_in: 0, total_scheduled: 0 },
      onPermission: +(activePermCount[0]?.cnt ?? 0),
      liveSprinklr,
      capturedAt: snap?.capturedAt ?? null,
    };
  }

  // ── Agent Timeline (working hours tracker) ────────────────────────────────
  async getAgentTimeline(tenantId: string, hours = 10) {
    try {
      // Take the LATEST snapshots then restore chronological order — ASC+LIMIT
      // would truncate to the oldest slice and silently drop today's data.
      const snapshots: { captured_at: string; agents_json: any }[] =
        (await this.dataSource.query(
          `SELECT captured_at, agents_json
           FROM integration_snapshots
           WHERE tenant_id = $1 AND source = 'sprinklr'
             AND captured_at >= NOW() - ($2 || ' hours')::interval
           ORDER BY captured_at DESC
           LIMIT 2000`,
          [tenantId, hours],
        )).reverse();

      if (!snapshots.length) return [];

      const agentMap: Record<string, {
        name: string;
        firstSeen: string;
        lastSeen: string;
        statusMinutes: Record<string, number>;
        loginTime: string | null;
      }> = {};

      for (let i = 1; i < snapshots.length; i++) {
        const prev = snapshots[i - 1];
        const curr = snapshots[i];
        const gapMinutes = (new Date(curr.captured_at).getTime() - new Date(prev.captured_at).getTime()) / 60000;
        if (gapMinutes > 5) continue; // skip large gaps (extension was closed)

        const agents: any[] = Array.isArray(curr.agents_json)
          ? curr.agents_json
          : JSON.parse(curr.agents_json || '[]');

        for (const a of agents) {
          if (!a.agentId) continue;
          if (isSyntheticAgent(a)) continue; // skip DOM-scrape placeholder rows
          if (!agentMap[a.agentId]) {
            const initName = (a.agentName && !isSyntheticName(a.agentName)) ? a.agentName : a.agentId;
            agentMap[a.agentId] = {
              name: initName,
              firstSeen: prev.captured_at,
              lastSeen: curr.captured_at,
              statusMinutes: {},
              loginTime: a.loginTime || null,
            };
          }
          const ag = agentMap[a.agentId];
          ag.lastSeen = curr.captured_at;
          // Only accept real names — reject DOM-scraping synthetic names
          if (a.agentName && !isSyntheticName(a.agentName)) {
            ag.name = a.agentName;
          }
          const st = a.status || 'unknown';
          ag.statusMinutes[st] = (ag.statusMinutes[st] ?? 0) + gapMinutes;
        }
      }

      return Object.entries(agentMap).map(([agentId, d]) => {
        // idle = available but not handling conversations → counts as working time (agent IS logged in)
        // In Sprinklr, 'available' = ready but not on a case → WFM idle
        // 'busy' = actively handling a case → WFM working
        const idleMins    = (d.statusMinutes['available'] ?? 0) + (d.statusMinutes['idle'] ?? 0);
        const busyMins    = (d.statusMinutes['busy']      ?? 0);
        const workingMins = idleMins + busyMins;
        const breakMins   = (d.statusMinutes['break'] ?? 0) + (d.statusMinutes['away'] ?? 0);
        const totalMins   = Object.values(d.statusMinutes).reduce((s, v) => s + v, 0);
        return {
          agentId,
          name: d.name,
          // loginTime from snapshot if captured, otherwise use firstSeen as proxy
          loginTime: d.loginTime || d.firstSeen,
          firstSeen: d.firstSeen,
          lastSeen: d.lastSeen,
          workingMinutes: Math.round(workingMins),
          idleMinutes:    Math.round(idleMins),
          busyMinutes:    Math.round(busyMins),
          breakMinutes:   Math.round(breakMins),
          totalTrackedMinutes: Math.round(totalMins),
          utilizationPct: totalMins > 0 ? Math.round((busyMins / totalMins) * 100) : 0,
          statusMinutes: Object.fromEntries(
            Object.entries(d.statusMinutes).map(([k, v]) => [k, Math.round(v)]),
          ),
        };
      }).sort((a, b) => b.workingMinutes - a.workingMinutes);
    } catch {
      return [];
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  AGENT ↔ EMPLOYEE MAPPING (lookup by email: sprinklr → users → employees)
  // ═══════════════════════════════════════════════════════════════════════════
  /**
   * Resolve a Sprinklr agent to a system employee.
   * 1. Exact: users.email → users.employee_id (when the agent has a WFM account).
   * 2. Heuristic (dual-signal, NOT name-alone): corporate email pattern
   *    f.lastname@boutiqaat.com — first initial + surname must BOTH match the
   *    employee record, and the match must be unique.
   */
  private async resolveEmployeeId(tenantId: string, email: string, agentName: string): Promise<string | null> {
    if (!email) return null;

    const rows = await this.dataSource.query(
      `SELECT employee_id FROM users
       WHERE tenant_id = $1 AND lower(email) = lower($2) AND employee_id IS NOT NULL LIMIT 1`,
      [tenantId, email],
    );
    if (rows?.length) return rows[0].employee_id;

    const m = email.toLowerCase().match(/^([a-z])\.([a-z]+)@/);
    if (!m) return null;
    const [, initial, emailLast] = m;

    // Initial must match first name; full normalized name must end with the email surname
    // (handles split surnames like "Abeer Al" + "shemari" → abeeralshemari ends with alshemari)
    const cand = await this.dataSource.query(
      `SELECT id, lower(first_name_en) AS fn FROM employees
       WHERE tenant_id = $1
         AND lower(left(first_name_en, 1)) = $2
         AND regexp_replace(lower(coalesce(first_name_en,'') || coalesce(last_name_en,'')), '[^a-z]', '', 'g')
             LIKE '%' || $3`,
      [tenantId, initial, emailLast],
    );
    if (cand?.length === 1) return cand[0].id;

    // Multiple candidates → disambiguate with the agent's display first name
    if (cand?.length > 1 && agentName) {
      const firstWord = agentName.trim().split(/\s+/)[0].toLowerCase();
      const exact = cand.filter((c: any) => c.fn === firstWord);
      if (exact.length === 1) return exact[0].id;
    }

    // Reversed corporate pattern: lastInitial.firstname@ (e.g. "Saleh Hassan" → h.saleh@)
    // Initial must match the LAST name; email surname part must equal the first name.
    const rev = await this.dataSource.query(
      `SELECT id FROM employees
       WHERE tenant_id = $1
         AND lower(left(coalesce(last_name_en, first_name_en), 1)) = $2
         AND regexp_replace(lower(coalesce(first_name_en,'')), '[^a-z]', '', 'g') = $3`,
      [tenantId, initial, emailLast],
    );
    if (rev?.length === 1) return rev[0].id;

    return null;
  }

  private async upsertAgentMap(tenantId: string, agents: SprinklrAgent[]): Promise<void> {
    const real = agents.filter(a =>
      a.agentId && /^\d{4,}$/.test(a.agentId) &&
      a.agentName && !isSyntheticName(a.agentName),
    );
    for (const a of real) {
      try {
        // Resolve user/employee by email when available
        let userId: string | null = null;
        let employeeId: string | null = null;
        if (a.email) {
          const rows = await this.dataSource.query(
            `SELECT id, employee_id FROM users
             WHERE tenant_id = $1 AND lower(email) = lower($2) LIMIT 1`,
            [tenantId, a.email],
          );
          if (rows?.length) { userId = rows[0].id; employeeId = rows[0].employee_id; }
          if (!employeeId) {
            employeeId = await this.resolveEmployeeId(tenantId, a.email, a.agentName);
          }
        }
        await this.dataSource.query(
          `INSERT INTO sprinklr_agent_map
             (tenant_id, sprinklr_agent_id, agent_name, agent_email, user_id, employee_id, last_seen)
           VALUES ($1, $2, $3, NULLIF($4,''), $5, $6, NOW())
           ON CONFLICT (tenant_id, sprinklr_agent_id) DO UPDATE SET
             agent_name  = EXCLUDED.agent_name,
             agent_email = COALESCE(EXCLUDED.agent_email, sprinklr_agent_map.agent_email),
             user_id     = COALESCE(EXCLUDED.user_id,     sprinklr_agent_map.user_id),
             employee_id = COALESCE(EXCLUDED.employee_id, sprinklr_agent_map.employee_id),
             last_seen   = NOW()`,
          [tenantId, a.agentId, a.agentName, a.email || '', userId, employeeId],
        );
      } catch (e: any) {
        this.logger.warn(`Agent map upsert failed for ${a.agentId}: ${e.message}`);
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  DAILY ROLLUP — per-agent stats computed from the snapshot timeline
  // ═══════════════════════════════════════════════════════════════════════════
  // Sprinklr measurement keys vary by widget; map them heuristically.
  private pickMetric(metrics: Record<string, number>, patterns: RegExp[]): number | null {
    for (const re of patterns) {
      for (const [k, v] of Object.entries(metrics)) {
        if (re.test(k) && typeof v === 'number' && v >= 0) return v;
      }
    }
    return null;
  }

  // Sprinklr times often come in milliseconds — normalize to seconds.
  private toSeconds(v: number | null): number | null {
    if (v == null) return null;
    return v > 100_000 ? Math.round(v / 1000) : Math.round(v);
  }

  async computeDailyStats(tenantId: string, date: string): Promise<{ agents: number }> {
    // Kuwait operational day boundaries (UTC+3)
    const dayStart = `${date}T00:00:00+03:00`;
    const dayEnd   = `${date}T23:59:59.999+03:00`;

    const snapshots: { captured_at: string; agents_json: any }[] =
      await this.dataSource.query(
        `SELECT captured_at, agents_json
         FROM integration_snapshots
         WHERE tenant_id = $1 AND source = 'sprinklr'
           AND captured_at BETWEEN $2::timestamptz AND $3::timestamptz
         ORDER BY captured_at ASC`,
        [tenantId, dayStart, dayEnd],
      );

    if (!snapshots.length) return { agents: 0 };

    type Acc = {
      name: string; email: string;
      firstLogin: string | null; lastLogout: string | null;
      statusMinutes: Record<string, number>;
      rawBreakdown: Record<string, number>;   // tea/lunch/bio/prayer/meeting/manual_dial/other_break
      idleNoCase: number; idleWithCase: number;
      lastMetrics: Record<string, number>;
    };
    const acc: Record<string, Acc> = {};

    // Categorize raw Sprinklr status labels into break/meeting/dial buckets
    const breakCategory = (raw: string, canonical: string): string | null => {
      const s = (raw || '').toLowerCase();
      if (s.includes('bio'))                                return 'bio_break';
      if (s.includes('lunch'))                              return 'lunch_break';
      if (s.includes('tea') || s.includes('short'))         return 'tea_break';
      if (s.includes('prayer'))                             return 'prayer_break';
      if (s.includes('meeting') || s.includes('huddle'))    return 'meeting';
      if (s.includes('training') || s.includes('coach'))    return 'training';
      if (s.includes('manual') || s.includes('outbound') || s.includes('dial')) return 'manual_dial';
      if (s.includes('break'))                              return 'other_break';
      if (canonical === 'break' || canonical === 'away')    return 'other_break';
      return null;
    };

    for (let i = 1; i < snapshots.length; i++) {
      const prev = snapshots[i - 1];
      const curr = snapshots[i];
      const gapMinutes = (new Date(curr.captured_at).getTime() - new Date(prev.captured_at).getTime()) / 60000;
      if (gapMinutes > 5) continue;

      const agents: any[] = Array.isArray(curr.agents_json)
        ? curr.agents_json : JSON.parse(curr.agents_json || '[]');

      for (const a of agents) {
        if (!a.agentId || isSyntheticAgent(a)) continue;
        if (!acc[a.agentId]) {
          acc[a.agentId] = {
            name: (a.agentName && !isSyntheticName(a.agentName)) ? a.agentName : a.agentId,
            email: a.email || '',
            firstLogin: null, lastLogout: null,
            statusMinutes: {}, rawBreakdown: {}, idleNoCase: 0, idleWithCase: 0,
            lastMetrics: {},
          };
        }
        const g = acc[a.agentId];
        if (a.agentName && !isSyntheticName(a.agentName)) g.name = a.agentName;
        if (a.email) g.email = a.email;
        if (a.metrics) g.lastMetrics = { ...g.lastMetrics, ...a.metrics };

        const st = a.status || 'unknown';
        g.statusMinutes[st] = (g.statusMinutes[st] ?? 0) + gapMinutes;

        // Raw break/meeting/dial categorization (Bio Break, Lunch, Tea, Prayer, Meeting, Manual Dial…)
        const cat = breakCategory(a.statusRaw || '', st);
        if (cat) g.rawBreakdown[cat] = (g.rawBreakdown[cat] ?? 0) + gapMinutes;

        const online = st !== 'offline' && st !== 'unknown';
        if (online) {
          if (!g.firstLogin) g.firstLogin = prev.captured_at;
          g.lastLogout = curr.captured_at;
        }

        // Idle split: available/idle + does the agent currently hold a case?
        if (st === 'available' || st === 'idle') {
          const assigned = this.pickMetric(a.metrics || {}, [/ASSIGNED/, /OPEN_CASE/, /ACTIVE_CASE/]);
          if (assigned != null && assigned > 0) g.idleWithCase += gapMinutes;
          else g.idleNoCase += gapMinutes;
        }
      }
    }

    let saved = 0;
    for (const [agentId, g] of Object.entries(acc)) {
      // Skip rows that never resolved to a real agent name (widget labels, bare IDs)
      if (!g.name || g.name === agentId || isSyntheticName(g.name)) continue;
      const idle  = g.idleNoCase + g.idleWithCase;
      const busy  = g.statusMinutes['busy'] ?? 0;
      const off   = g.statusMinutes['offline'] ?? 0;

      // Daily break total = ALL break types combined (tea + lunch + bio + prayer + other).
      // Meetings/training/manual-dial are tracked separately — NOT part of the break total.
      const BREAK_KEYS = ['tea_break', 'lunch_break', 'bio_break', 'prayer_break', 'other_break'];
      const breakdownTotal = BREAK_KEYS.reduce((s, k) => s + (g.rawBreakdown[k] ?? 0), 0);
      const canonicalBrk   = (g.statusMinutes['break'] ?? 0) + (g.statusMinutes['away'] ?? 0);
      const brk = Math.max(breakdownTotal, canonicalBrk);
      const breakdown = {
        ...Object.fromEntries(Object.entries(g.rawBreakdown).map(([k, v]) => [k, Math.round(v)])),
        total_break: Math.round(brk),
      };

      const aht       = this.toSeconds(this.pickMetric(g.lastMetrics, [/HANDLE_TIME/, /\bAHT\b/, /HANDLING_TIME/]));
      const frt       = this.toSeconds(this.pickMetric(g.lastMetrics, [/FIRST_RESPONSE/, /\bFRT\b/, /RESPONSE_TIME/]));
      const contacts  = this.pickMetric(g.lastMetrics, [/CASE.*HANDLED/, /HANDLED.*CASE/, /CASE_COUNT/, /CASES_RECEIVED/, /MESSAGE_COUNT/, /CONTACT/]);

      // Resolve employee: persisted map first, then email/dual-signal resolver
      let employeeId: string | null = null;
      const mapped = await this.dataSource.query(
        `SELECT employee_id FROM sprinklr_agent_map
         WHERE tenant_id = $1 AND sprinklr_agent_id = $2 AND employee_id IS NOT NULL LIMIT 1`,
        [tenantId, agentId],
      );
      if (mapped?.length) {
        employeeId = mapped[0].employee_id;
      } else if (g.email) {
        employeeId = await this.resolveEmployeeId(tenantId, g.email, g.name);
        if (employeeId) {
          // Persist the resolved link so future lookups are instant
          await this.dataSource.query(
            `UPDATE sprinklr_agent_map SET employee_id = $3, last_seen = NOW()
             WHERE tenant_id = $1 AND sprinklr_agent_id = $2`,
            [tenantId, agentId, employeeId],
          ).catch(() => undefined);
        }
      }

      await this.dataSource.query(
        `INSERT INTO agent_daily_stats
           (tenant_id, stat_date, sprinklr_agent_id, agent_name, agent_email, employee_id,
            first_login, last_logout,
            total_working_minutes, idle_no_case_minutes, idle_with_case_minutes,
            busy_minutes, break_minutes, offline_minutes,
            contacts_received, aht_seconds, avg_response_seconds,
            status_minutes, extra, break_breakdown, computed_at)
         VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19::jsonb,$20::jsonb,NOW())
         ON CONFLICT (tenant_id, stat_date, sprinklr_agent_id) DO UPDATE SET
           agent_name             = EXCLUDED.agent_name,
           agent_email            = COALESCE(EXCLUDED.agent_email, agent_daily_stats.agent_email),
           employee_id            = COALESCE(EXCLUDED.employee_id, agent_daily_stats.employee_id),
           first_login            = EXCLUDED.first_login,
           last_logout            = EXCLUDED.last_logout,
           total_working_minutes  = EXCLUDED.total_working_minutes,
           idle_no_case_minutes   = EXCLUDED.idle_no_case_minutes,
           idle_with_case_minutes = EXCLUDED.idle_with_case_minutes,
           busy_minutes           = EXCLUDED.busy_minutes,
           break_minutes          = EXCLUDED.break_minutes,
           offline_minutes        = EXCLUDED.offline_minutes,
           contacts_received      = COALESCE(EXCLUDED.contacts_received, agent_daily_stats.contacts_received),
           aht_seconds            = COALESCE(EXCLUDED.aht_seconds, agent_daily_stats.aht_seconds),
           avg_response_seconds   = COALESCE(EXCLUDED.avg_response_seconds, agent_daily_stats.avg_response_seconds),
           status_minutes         = EXCLUDED.status_minutes,
           extra                  = EXCLUDED.extra,
           break_breakdown        = EXCLUDED.break_breakdown,
           computed_at            = NOW()`,
        [
          tenantId, date, agentId, g.name, g.email, employeeId,
          g.firstLogin, g.lastLogout,
          Math.round(idle + busy), Math.round(g.idleNoCase), Math.round(g.idleWithCase),
          Math.round(busy), Math.round(brk), Math.round(off),
          contacts, aht, frt,
          JSON.stringify(Object.fromEntries(Object.entries(g.statusMinutes).map(([k, v]) => [k, Math.round(v)]))),
          JSON.stringify(g.lastMetrics),
          JSON.stringify(breakdown),
        ],
      );
      saved++;
    }

    this.logger.log(`[${tenantId}] Daily stats computed for ${date}: ${saved} agents`);
    return { agents: saved };
  }

  // Throttle: auto-recompute today's stats at most once per 5 minutes after ingest
  private lastRollupAt = new Map<string, number>();

  private async maybeRollupToday(tenantId: string): Promise<void> {
    const last = this.lastRollupAt.get(tenantId) ?? 0;
    if (Date.now() - last < 5 * 60_000) return;
    this.lastRollupAt.set(tenantId, Date.now());
    const today = new Date(Date.now() + 3 * 3600e3).toISOString().slice(0, 10); // Kuwait UTC+3
    await this.computeDailyStats(tenantId, today).catch(e =>
      this.logger.warn(`Auto rollup failed: ${e.message}`));
    await this.computeViolations(tenantId, today).catch(e =>
      this.logger.warn(`Violations compute failed: ${e.message}`));
    await this.computeAdherence(tenantId, today).catch(e =>
      this.logger.warn(`Adherence compute failed: ${e.message}`));
    await this.harvestChannelDemand(tenantId, today).catch(e =>
      this.logger.warn(`Channel demand harvest failed: ${e.message}`));
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  CHANNEL DEMAND HARVEST — daily contact volumes per channel for the forecast.
  //  Sprinklr's workQueueStats carries cumulative daily counters (names vary by
  //  install). We mine every numeric key that looks like a work/case counter,
  //  take (max − min) over the day per queue (monotonic delta), and pick the
  //  best "received-like" counter; falls back to "completed-like".
  // ═══════════════════════════════════════════════════════════════════════════
  private async harvestChannelDemand(tenantId: string, date: string): Promise<void> {
    const snaps: { queues_json: any }[] = await this.dataSource.query(
      `SELECT queues_json FROM integration_snapshots
       WHERE tenant_id = $1 AND source = 'sprinklr'
         AND captured_at BETWEEN $2::date::timestamptz AND ($2::date::timestamptz + interval '24 hours')
       ORDER BY captured_at ASC`,
      [tenantId, date],
    );
    if (!snaps.length) return;

    const RECEIVED = /(received|created|total|incoming|new).*(work|case|message|contact)|(work|case|message|contact).*(received|created|total|incoming|new)/i;
    const HANDLED  = /(completed|closed|handled|resolved).*(work|case|message|contact)|(work|case|message|contact).*(completed|closed|handled|resolved)/i;

    // channel → { counterKey → {min,max} ; peakWaiting }
    type Track = { counters: Map<string, { min: number; max: number; kind: 'received' | 'handled' }>; peakWaiting: number };
    const byChannel = new Map<string, Track>();

    for (const s of snaps) {
      const queues: any[] = Array.isArray(s.queues_json) ? s.queues_json : JSON.parse(s.queues_json || '[]');
      for (const q of queues) {
        const ch = q.channel || 'unknown';
        const t = byChannel.get(ch) ?? { counters: new Map(), peakWaiting: 0 };
        t.peakWaiting = Math.max(t.peakWaiting, q.waiting ?? 0);
        const raw = q.statsRaw;
        if (raw && typeof raw === 'object') {
          for (const [k, v] of Object.entries(raw)) {
            if (typeof v !== 'number' || !Number.isFinite(v) || v < 0) continue;
            const kind = RECEIVED.test(k) ? 'received' : HANDLED.test(k) ? 'handled' : null;
            if (!kind) continue;
            const key = `${q.queueId}|${k}`;
            const c = t.counters.get(key) ?? { min: v, max: v, kind };
            c.min = Math.min(c.min, v); c.max = Math.max(c.max, v);
            t.counters.set(key, c);
          }
        }
        byChannel.set(ch, t);
      }
    }

    for (const [ch, t] of byChannel) {
      // Sum deltas per queue, preferring received-like counters
      const perQueueBest = new Map<string, { delta: number; kind: string }>();
      for (const [key, c] of t.counters) {
        const queueId = key.split('|')[0];
        const delta = c.max - c.min;
        const cur = perQueueBest.get(queueId);
        const better = !cur
          || (c.kind === 'received' && cur.kind !== 'received')
          || (c.kind === cur.kind && delta > cur.delta);
        if (better) perQueueBest.set(queueId, { delta, kind: c.kind });
      }
      const contacts = [...perQueueBest.values()].reduce((s, x) => s + x.delta, 0);

      await this.dataSource.query(
        `INSERT INTO channel_demand_daily (tenant_id, demand_date, channel, contacts, peak_waiting, source)
         VALUES ($1, $2::date, $3, $4, $5, 'sprinklr')
         ON CONFLICT (tenant_id, demand_date, channel) DO UPDATE SET
           contacts = GREATEST(EXCLUDED.contacts, channel_demand_daily.contacts),
           peak_waiting = GREATEST(EXCLUDED.peak_waiting, channel_demand_daily.peak_waiting),
           computed_at = NOW()`,
        [tenantId, date, ch, Math.round(contacts), t.peakWaiting],
      );
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  COMPLIANCE / VIOLATIONS ENGINE
  //  excess_break · late_login · early_logout · off_schedule ·
  //  unauthorized_meeting · unauthorized_manual_dial
  // ═══════════════════════════════════════════════════════════════════════════
  // Defaults — overridable per tenant via settings key 'compliance_config'
  private static readonly COMPLIANCE_DEFAULTS = {
    breakLimitMin:  60,  // daily break allowance (all types combined)
    lateGraceMin:   10,  // grace period for login after shift start
    earlyGraceMin:  10,  // grace period for logout before shift end
    meetingMinFlag: 15,  // meeting minutes before flagging
    dialMinFlag:    5,   // manual-dial minutes before flagging
  };

  async getComplianceConfig(tenantId: string) {
    try {
      const rows = await this.dataSource.query(
        `SELECT setting_value FROM tenant_settings
         WHERE tenant_id = $1 AND setting_key = 'compliance_config' LIMIT 1`,
        [tenantId],
      );
      const v = rows?.[0]?.setting_value;
      const saved = v ? (typeof v === 'object' ? v : JSON.parse(v)) : {};
      return { ...SprinklrService.COMPLIANCE_DEFAULTS, ...saved };
    } catch {
      return { ...SprinklrService.COMPLIANCE_DEFAULTS };
    }
  }

  async saveComplianceConfig(tenantId: string, config: Partial<typeof SprinklrService.COMPLIANCE_DEFAULTS>) {
    // Sanitize: numeric, sane bounds
    const clean: Record<string, number> = {};
    for (const key of Object.keys(SprinklrService.COMPLIANCE_DEFAULTS) as (keyof typeof SprinklrService.COMPLIANCE_DEFAULTS)[]) {
      const v = Number(config[key]);
      if (Number.isFinite(v) && v >= 0 && v <= 480) clean[key] = Math.round(v);
    }
    await this.dataSource.query(
      `INSERT INTO tenant_settings (tenant_id, setting_key, setting_value, setting_group, updated_at)
       VALUES ($1, 'compliance_config', $2::jsonb, 'compliance', NOW())
       ON CONFLICT (tenant_id, setting_key) DO UPDATE SET setting_value = $2::jsonb, updated_at = NOW()`,
      [tenantId, JSON.stringify(clean)],
    );
    return this.getComplianceConfig(tenantId);
  }

  async computeViolations(tenantId: string, date: string): Promise<{ violations: number }> {
    const cfg = await this.getComplianceConfig(tenantId);

    // 1. Daily stats for the date (already linked to employees by email)
    const stats: any[] = await this.dataSource.query(
      `SELECT * FROM agent_daily_stats
       WHERE tenant_id = $1 AND stat_date = $2::date`,
      [tenantId, date],
    );
    if (!stats.length) return { violations: 0 };

    // Tracking coverage — we can only judge what the extension actually observed.
    // Snapshots arrive every ~30s while tracking is on, so "tracking covered moment X"
    // means a snapshot exists NEAR X. A snapshot hours earlier followed by a gap
    // (extension closed) must NOT count as coverage.
    const snapTimes: { captured_at: string }[] = await this.dataSource.query(
      `SELECT captured_at FROM integration_snapshots
       WHERE tenant_id = $1 AND source = 'sprinklr'
         AND captured_at BETWEEN ($2::date::timestamptz - interval '9 hours')
                             AND ($2::date::timestamptz + interval '33 hours')
       ORDER BY captured_at ASC`,
      [tenantId, date],
    );
    const snapMs = snapTimes.map(r => new Date(r.captured_at).getTime());
    const hasSnapNear = (ms: number, beforeTolMin: number, afterTolMin: number) =>
      snapMs.some(t => t >= ms - beforeTolMin * 60000 && t <= ms + afterTolMin * 60000);

    // Remove stale OPEN violations for the date — they get recomputed fresh below.
    // Reviewed/justified ones are kept (human decisions are never auto-deleted).
    await this.dataSource.query(
      `DELETE FROM agent_violations
       WHERE tenant_id = $1 AND violation_date = $2::date AND status = 'open'`,
      [tenantId, date],
    );

    // 2. Scheduled shifts for the date (TIME columns → timestamptz, cross-midnight aware)
    const schedules: any[] = await this.dataSource.query(
      `SELECT ar.employee_id,
              CASE WHEN ar.scheduled_start IS NOT NULL
                   THEN (ar.attendance_date::text || ' ' || ar.scheduled_start::text || '+03')::timestamptz
              END AS scheduled_start,
              CASE WHEN ar.scheduled_end IS NULL THEN NULL
                   WHEN ar.scheduled_end <= ar.scheduled_start
                   THEN ((ar.attendance_date + 1)::text || ' ' || ar.scheduled_end::text || '+03')::timestamptz
                   ELSE (ar.attendance_date::text  || ' ' || ar.scheduled_end::text || '+03')::timestamptz
              END AS scheduled_end,
              sc.code AS shift_code, sc.is_working_shift, sc.is_leave_code
       FROM attendance_records ar
       LEFT JOIN shift_codes sc ON sc.id = ar.scheduled_shift_code_id
       WHERE ar.tenant_id = $1 AND ar.attendance_date = $2::date`,
      [tenantId, date],
    );
    const schedByEmp = new Map(schedules.map(s => [s.employee_id, s]));

    // 3. Approved permissions / break requests for the date, per employee
    const perms: any[] = await this.dataSource.query(
      `SELECT r.employee_id, rt.code AS req_type, rp.start_time, rp.end_time
       FROM requests r
       JOIN request_types rt ON rt.id = r.request_type_id
       LEFT JOIN request_permissions rp ON rp.request_id = r.id
       WHERE r.tenant_id = $1 AND r.status = 'approved'
         AND (rp.permission_date = $2::date OR rp.permission_date IS NULL AND r.created_at::date = $2::date)`,
      [tenantId, date],
    );
    const permsByEmp = new Map<string, any[]>();
    perms.forEach(p => {
      if (!p.employee_id) return;
      const arr = permsByEmp.get(p.employee_id) || [];
      arr.push(p);
      permsByEmp.set(p.employee_id, arr);
    });
    const hasApproval = (employeeId: string | null) =>
      !!employeeId && (permsByEmp.get(employeeId)?.length ?? 0) > 0;

    const sev = (mins: number, lo: number, hi: number) =>
      mins >= hi ? 'high' : mins >= lo ? 'medium' : 'low';

    type V = {
      type: string; severity: string; minutes: number | null;
      shiftStart?: string | null; shiftEnd?: string | null; actualAt?: string | null;
      details: Record<string, any>;
    };

    let count = 0;
    const newHigh: { id: string; agentName: string; type: string; minutes: number | null }[] = [];
    for (const s of stats) {
      const breakdown = typeof s.break_breakdown === 'object'
        ? (s.break_breakdown || {}) : JSON.parse(s.break_breakdown || '{}');
      const sched = s.employee_id ? schedByEmp.get(s.employee_id) : null;
      const approved = hasApproval(s.employee_id);
      const violations: V[] = [];

      // ── excess_break: all break types combined > 60 min/day ──
      const totalBreak = +breakdown.total_break || +s.break_minutes || 0;
      if (totalBreak > cfg.breakLimitMin) {
        const excess = totalBreak - cfg.breakLimitMin;
        violations.push({
          type: 'excess_break',
          severity: sev(excess, 15, 45),
          minutes: excess,
          details: {
            totalBreakMinutes: totalBreak, limitMinutes: cfg.breakLimitMin,
            breakdown: {
              tea:    breakdown.tea_break    ?? 0, lunch: breakdown.lunch_break ?? 0,
              bio:    breakdown.bio_break    ?? 0, prayer: breakdown.prayer_break ?? 0,
              other:  breakdown.other_break  ?? 0,
            },
          },
        });
      }

      // ── late_login: first Sprinklr activity after scheduled shift start ──
      // Only judged when tracking already covered the shift start — otherwise the
      // agent may have been online before the extension started watching.
      const shiftStartMs = sched?.scheduled_start ? new Date(sched.scheduled_start).getTime() : null;
      // Coverage = a snapshot exists within [start, start + grace] (tracking live at shift start)
      const trackingCoveredStart = shiftStartMs != null
        && hasSnapNear(shiftStartMs, 0, cfg.lateGraceMin);
      if (sched?.scheduled_start && s.first_login && !approved && trackingCoveredStart) {
        const lateMin = Math.round(
          (new Date(s.first_login).getTime() - new Date(sched.scheduled_start).getTime()) / 60000);
        if (lateMin > cfg.lateGraceMin) {
          violations.push({
            type: 'late_login',
            severity: sev(lateMin, 30, 60),
            minutes: lateMin,
            shiftStart: sched.scheduled_start, actualAt: s.first_login,
            details: { shiftCode: sched.shift_code, graceMinutes: cfg.lateGraceMin },
          });
        }
      }

      // ── early_logout: last Sprinklr activity before scheduled shift end ──
      // Only judged when the shift has actually ENDED and tracking covered its end —
      // an in-progress shift must never count as "left early".
      const shiftEndMs = sched?.scheduled_end ? new Date(sched.scheduled_end).getTime() : null;
      const shiftOver  = shiftEndMs != null && Date.now() > shiftEndMs;
      // Coverage = a snapshot exists within [end - grace, end + 5] (tracking live at shift end)
      const trackingCoveredEnd = shiftEndMs != null && hasSnapNear(shiftEndMs, cfg.earlyGraceMin, 5);
      if (sched?.scheduled_end && s.last_logout && !approved && shiftOver && trackingCoveredEnd) {
        const earlyMin = Math.round(
          (new Date(sched.scheduled_end).getTime() - new Date(s.last_logout).getTime()) / 60000);
        if (earlyMin > cfg.earlyGraceMin) {
          violations.push({
            type: 'early_logout',
            severity: sev(earlyMin, 30, 60),
            minutes: earlyMin,
            shiftEnd: sched.scheduled_end, actualAt: s.last_logout,
            details: { shiftCode: sched.shift_code, graceMinutes: cfg.earlyGraceMin },
          });
        }
      }

      // ── off_schedule: active on Sprinklr but no working shift scheduled ──
      if (s.employee_id && s.total_working_minutes > 30) {
        const noShift   = !sched;
        const leaveDay  = sched && (sched.is_leave_code || sched.is_working_shift === false);
        if (noShift || leaveDay) {
          violations.push({
            type: 'off_schedule',
            severity: 'medium',
            minutes: s.total_working_minutes,
            details: {
              reason: noShift ? 'no_scheduled_shift' : 'scheduled_off_or_leave',
              shiftCode: sched?.shift_code ?? null,
              workedMinutes: s.total_working_minutes,
            },
          });
        }
      }

      // ── unauthorized_meeting: meeting status without an approved request ──
      const meetingMin = (+breakdown.meeting || 0) + (+breakdown.training || 0);
      if (meetingMin >= cfg.meetingMinFlag && !approved) {
        violations.push({
          type: 'unauthorized_meeting',
          severity: sev(meetingMin, 30, 60),
          minutes: Math.round(meetingMin),
          details: { meetingMinutes: Math.round(+breakdown.meeting || 0), trainingMinutes: Math.round(+breakdown.training || 0) },
        });
      }

      // ── unauthorized_manual_dial: manual/outbound dial without approval ──
      const dialMin = +breakdown.manual_dial || 0;
      if (dialMin >= cfg.dialMinFlag && !approved) {
        violations.push({
          type: 'unauthorized_manual_dial',
          severity: sev(dialMin, 20, 45),
          minutes: Math.round(dialMin),
          details: { manualDialMinutes: Math.round(dialMin) },
        });
      }

      // Upsert all violations for this agent/date
      for (const v of violations) {
        const res = await this.dataSource.query(
          `INSERT INTO agent_violations
             (tenant_id, violation_date, sprinklr_agent_id, agent_name, agent_email, employee_id,
              violation_type, severity, minutes, shift_start, shift_end, actual_at, details)
           VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,$8,$9,$10,$11,$12,$13::jsonb)
           ON CONFLICT (tenant_id, violation_date, sprinklr_agent_id, violation_type) DO UPDATE SET
             agent_name  = EXCLUDED.agent_name,
             agent_email = COALESCE(EXCLUDED.agent_email, agent_violations.agent_email),
             employee_id = COALESCE(EXCLUDED.employee_id, agent_violations.employee_id),
             severity    = EXCLUDED.severity,
             minutes     = EXCLUDED.minutes,
             shift_start = EXCLUDED.shift_start,
             shift_end   = EXCLUDED.shift_end,
             actual_at   = EXCLUDED.actual_at,
             details     = EXCLUDED.details
           RETURNING id, (xmax = 0) AS is_new`,
          [
            tenantId, date, s.sprinklr_agent_id, s.agent_name, s.agent_email || '', s.employee_id,
            v.type, v.severity, v.minutes,
            v.shiftStart ?? null, v.shiftEnd ?? null, v.actualAt ?? null,
            JSON.stringify(v.details),
          ],
        );
        count++;
        if (res?.[0]?.is_new && v.severity === 'high') {
          newHigh.push({ id: res[0].id, agentName: s.agent_name, type: v.type, minutes: v.minutes });
        }
      }
    }

    // Notify WFM/RTA users about NEW high-severity violations (deduped by violation id)
    if (newHigh.length) {
      await this.notifyViolations(tenantId, date, newHigh).catch(e =>
        this.logger.warn(`Violation notifications failed: ${e.message}`));
    }

    this.logger.log(`[${tenantId}] Violations computed for ${date}: ${count} (${newHigh.length} new high)`);
    return { violations: count };
  }

  private static readonly VIOLATION_LABELS: Record<string, { en: string; ar: string }> = {
    excess_break:             { en: 'Excess break (>limit)',     ar: 'بريك زائد عن الحد' },
    late_login:               { en: 'Late login',                ar: 'تأخير عن الشفت' },
    early_logout:             { en: 'Early logout',              ar: 'خروج مبكر' },
    off_schedule:             { en: 'Off-schedule activity',     ar: 'شغل خارج الجدول' },
    unauthorized_meeting:     { en: 'Unauthorized meeting',      ar: 'ميتنج بدون موافقة' },
    unauthorized_manual_dial: { en: 'Unauthorized manual dial',  ar: 'Manual Dial بدون إذن' },
  };

  private async notifyViolations(
    tenantId: string, date: string,
    items: { id: string; agentName: string; type: string; minutes: number | null }[],
  ): Promise<void> {
    // Recipients: active WFM / RTA / admin users
    const recipients: { id: string }[] = await this.dataSource.query(
      `SELECT DISTINCT u.id FROM users u
       JOIN user_roles ur ON ur.user_id = u.id
       JOIN roles r ON r.id = ur.role_id
       WHERE u.tenant_id = $1 AND u.status = 'active'
         AND r.code IN ('wfm_analyst', 'rta', 'platform_admin')`,
      [tenantId],
    );
    if (!recipients.length) return;

    for (const it of items) {
      const label = SprinklrService.VIOLATION_LABELS[it.type] ?? { en: it.type, ar: it.type };
      const mins  = it.minutes != null ? ` (${it.minutes} min)` : '';
      const minsAr = it.minutes != null ? ` (${it.minutes} دقيقة)` : '';
      for (const r of recipients) {
        await this.dataSource.query(
          `INSERT INTO notifications
             (tenant_id, recipient_id, notification_type, title, title_ar, body, body_ar,
              entity_type, entity_id, action_url)
           VALUES ($1,$2,'violation',$3,$4,$5,$6,'agent_violation',$7,'/rta')`,
          [
            tenantId, r.id,
            `Violation: ${label.en}`, `مخالفة: ${label.ar}`,
            `${it.agentName} — ${label.en}${mins} on ${date}`,
            `${it.agentName} — ${label.ar}${minsAr} بتاريخ ${date}`,
            it.id,
          ],
        );
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  SCHEDULE ADHERENCE ENGINE — scheduled shift vs actual Sprinklr activity
  // ═══════════════════════════════════════════════════════════════════════════
  async computeAdherence(tenantId: string, date: string): Promise<{ employees: number }> {
    // 1. Scheduled working shifts for the date.
    // scheduled_start/end are TIME columns — combine with the date (Kuwait +03)
    // and roll cross-midnight shift ends to the next day.
    const schedules: any[] = await this.dataSource.query(
      `SELECT ar.employee_id,
              (ar.attendance_date::text || ' ' || ar.scheduled_start::text || '+03')::timestamptz AS scheduled_start,
              CASE WHEN ar.scheduled_end <= ar.scheduled_start
                   THEN ((ar.attendance_date + 1)::text || ' ' || ar.scheduled_end::text || '+03')::timestamptz
                   ELSE (ar.attendance_date::text  || ' ' || ar.scheduled_end::text || '+03')::timestamptz
              END AS scheduled_end,
              sc.code AS shift_code,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name
       FROM attendance_records ar
       JOIN employees e ON e.id = ar.employee_id
       LEFT JOIN shift_codes sc ON sc.id = ar.scheduled_shift_code_id
       WHERE ar.tenant_id = $1 AND ar.attendance_date = $2::date
         AND ar.scheduled_start IS NOT NULL AND ar.scheduled_end IS NOT NULL`,
      [tenantId, date],
    );
    if (!schedules.length) return { employees: 0 };

    // 2. Employee → Sprinklr agent mapping
    const maps: any[] = await this.dataSource.query(
      `SELECT employee_id, sprinklr_agent_id, agent_name FROM sprinklr_agent_map
       WHERE tenant_id = $1 AND employee_id IS NOT NULL`,
      [tenantId],
    );
    const agentByEmp = new Map(maps.map(m => [m.employee_id, m]));

    // 3. Snapshots covering the operational day ±6h (cross-midnight shifts)
    const snapshots: { captured_at: string; agents_json: any }[] =
      await this.dataSource.query(
        `SELECT captured_at, agents_json FROM integration_snapshots
         WHERE tenant_id = $1 AND source = 'sprinklr'
           AND captured_at BETWEEN ($2::date::timestamptz - interval '9 hours')
                               AND ($2::date::timestamptz + interval '33 hours')
         ORDER BY captured_at ASC`,
        [tenantId, date],
      );

    // Build per-agent status timeline segments [(fromMs, toMs, state)]
    const ONLINE = new Set(['available', 'idle', 'busy']);
    const BREAKS = new Set(['break', 'away']);
    type Seg = { from: number; to: number; state: 'online' | 'break' | 'offline' };
    const timeline = new Map<string, Seg[]>();

    for (let i = 1; i < snapshots.length; i++) {
      const prev = snapshots[i - 1];
      const curr = snapshots[i];
      const fromMs = new Date(prev.captured_at).getTime();
      const toMs   = new Date(curr.captured_at).getTime();
      if (toMs - fromMs > 5 * 60_000) continue;   // gap → untracked, skip

      const agents: any[] = Array.isArray(curr.agents_json)
        ? curr.agents_json : JSON.parse(curr.agents_json || '[]');
      for (const a of agents) {
        if (!a.agentId || isSyntheticAgent(a)) continue;
        const st = ONLINE.has(a.status) ? 'online' : BREAKS.has(a.status) ? 'break' : 'offline';
        const segs = timeline.get(a.agentId) || [];
        const last = segs[segs.length - 1];
        if (last && last.state === st && last.to === fromMs) last.to = toMs;  // extend
        else segs.push({ from: fromMs, to: toMs, state: st as Seg['state'] });
        timeline.set(a.agentId, segs);
      }
    }

    let saved = 0;
    for (const sch of schedules) {
      const map = agentByEmp.get(sch.employee_id);
      const shiftStart = new Date(sch.scheduled_start).getTime();
      const shiftEnd   = new Date(sch.scheduled_end).getTime();
      const scheduledMin = Math.round((shiftEnd - shiftStart) / 60000);
      if (scheduledMin <= 0) continue;

      let inAdh = 0, brk = 0, off = 0, tracked = 0, workedTotal = 0;
      const deviations: { from: string; to: string; state: string }[] = [];

      const segs = map ? (timeline.get(map.sprinklr_agent_id) || []) : [];
      for (const s of segs) {
        // total online of the day (conformance)
        if (s.state === 'online') workedTotal += (s.to - s.from) / 60000;

        // overlap with the scheduled shift (adherence)
        const oFrom = Math.max(s.from, shiftStart);
        const oTo   = Math.min(s.to, shiftEnd);
        if (oTo <= oFrom) continue;
        const mins = (oTo - oFrom) / 60000;
        tracked += mins;
        if (s.state === 'online')      inAdh += mins;
        else if (s.state === 'break')  brk   += mins;
        else                           off   += mins;
        if (s.state !== 'online' && mins >= 5) {
          deviations.push({
            from: new Date(oFrom).toISOString(),
            to:   new Date(oTo).toISOString(),
            state: s.state,
          });
        }
      }

      const adherencePct  = tracked > 0 ? +((inAdh / tracked) * 100).toFixed(1) : null;
      const conformancePct = +(Math.min(150, (workedTotal / scheduledMin) * 100)).toFixed(1);

      await this.dataSource.query(
        `INSERT INTO adherence_daily
           (tenant_id, stat_date, employee_id, sprinklr_agent_id, agent_name, shift_code,
            scheduled_start, scheduled_end,
            scheduled_minutes, tracked_minutes, in_adherence_minutes,
            break_in_shift_minutes, offline_in_shift_minutes, worked_total_minutes,
            adherence_pct, conformance_pct, deviations, computed_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::jsonb,NOW())
         ON CONFLICT (tenant_id, stat_date, employee_id) DO UPDATE SET
           sprinklr_agent_id        = EXCLUDED.sprinklr_agent_id,
           agent_name               = EXCLUDED.agent_name,
           shift_code               = EXCLUDED.shift_code,
           scheduled_start          = EXCLUDED.scheduled_start,
           scheduled_end            = EXCLUDED.scheduled_end,
           scheduled_minutes        = EXCLUDED.scheduled_minutes,
           tracked_minutes          = EXCLUDED.tracked_minutes,
           in_adherence_minutes     = EXCLUDED.in_adherence_minutes,
           break_in_shift_minutes   = EXCLUDED.break_in_shift_minutes,
           offline_in_shift_minutes = EXCLUDED.offline_in_shift_minutes,
           worked_total_minutes     = EXCLUDED.worked_total_minutes,
           adherence_pct            = EXCLUDED.adherence_pct,
           conformance_pct          = EXCLUDED.conformance_pct,
           deviations               = EXCLUDED.deviations,
           computed_at              = NOW()`,
        [
          tenantId, date, sch.employee_id,
          map?.sprinklr_agent_id ?? null, map?.agent_name ?? sch.employee_name, sch.shift_code,
          sch.scheduled_start, sch.scheduled_end,
          scheduledMin, Math.round(tracked), Math.round(inAdh),
          Math.round(brk), Math.round(off), Math.round(workedTotal),
          adherencePct, conformancePct, JSON.stringify(deviations.slice(0, 50)),
        ],
      );
      saved++;
    }

    this.logger.log(`[${tenantId}] Adherence computed for ${date}: ${saved} employees`);
    return { employees: saved };
  }

  async getAdherenceReport(tenantId: string, from: string, to: string, refresh = false) {
    if (refresh) {
      const start = new Date(from); const end = new Date(to);
      for (let d = new Date(start), i = 0; d <= end && i < 31; d.setDate(d.getDate() + 1), i++) {
        await this.computeAdherence(tenantId, d.toISOString().slice(0, 10));
      }
    }

    const rows = await this.dataSource.query(
      `SELECT a.*, e.employee_no,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name
       FROM adherence_daily a
       JOIN employees e ON e.id = a.employee_id
       WHERE a.tenant_id = $1 AND a.stat_date BETWEEN $2::date AND $3::date
       ORDER BY a.stat_date DESC, a.adherence_pct ASC NULLS LAST`,
      [tenantId, from, to],
    );

    const measured = rows.filter((r: any) => r.adherence_pct != null);
    const avg = (k: string) => measured.length
      ? +(measured.reduce((s: number, r: any) => s + +r[k], 0) / measured.length).toFixed(1) : null;

    return {
      from, to,
      summary: {
        employees:       rows.length,
        measured:        measured.length,        // had Sprinklr tracking during shift
        unmatched:       rows.filter((r: any) => !r.sprinklr_agent_id).length,
        avgAdherence:    avg('adherence_pct'),
        avgConformance:  avg('conformance_pct'),
        below85:         measured.filter((r: any) => +r.adherence_pct < 85).length,
      },
      rows,
    };
  }

  // Intraday: scheduled HC vs actual online HC per 30-min interval
  async getAdherenceIntraday(tenantId: string, date: string) {
    const schedules: any[] = await this.dataSource.query(
      `SELECT (attendance_date::text || ' ' || scheduled_start::text || '+03')::timestamptz AS scheduled_start,
              CASE WHEN scheduled_end <= scheduled_start
                   THEN ((attendance_date + 1)::text || ' ' || scheduled_end::text || '+03')::timestamptz
                   ELSE (attendance_date::text  || ' ' || scheduled_end::text || '+03')::timestamptz
              END AS scheduled_end
       FROM attendance_records
       WHERE tenant_id = $1 AND attendance_date = $2::date
         AND scheduled_start IS NOT NULL AND scheduled_end IS NOT NULL`,
      [tenantId, date],
    );

    const snapshots: any[] = await this.dataSource.query(
      `SELECT captured_at, agents_json FROM integration_snapshots
       WHERE tenant_id = $1 AND source = 'sprinklr'
         AND captured_at BETWEEN $2::date::timestamptz AND ($2::date::timestamptz + interval '24 hours')
       ORDER BY captured_at ASC`,
      [tenantId, date],
    );

    const ONLINE = new Set(['available', 'idle', 'busy']);
    const dayStart = new Date(`${date}T00:00:00+03:00`).getTime();
    const intervals = Array.from({ length: 48 }, (_, i) => {
      const from = dayStart + i * 30 * 60000;
      const to   = from + 30 * 60000;
      const scheduled = schedules.filter(s =>
        new Date(s.scheduled_start).getTime() < to &&
        new Date(s.scheduled_end).getTime()   > from,
      ).length;

      // actual = average distinct online agents across snapshots in the interval
      const snaps = snapshots.filter(s => {
        const t = new Date(s.captured_at).getTime();
        return t >= from && t < to;
      });
      let actual: number | null = null;
      if (snaps.length) {
        const counts = snaps.map(s => {
          const agents: any[] = Array.isArray(s.agents_json) ? s.agents_json : JSON.parse(s.agents_json || '[]');
          return agents.filter(a => !isSyntheticAgent(a) && ONLINE.has(a.status)).length;
        });
        actual = Math.round(counts.reduce((x, y) => x + y, 0) / counts.length);
      }

      const hh = String(Math.floor(i / 2)).padStart(2, '0');
      const mm = i % 2 === 0 ? '00' : '30';
      return { interval: `${hh}:${mm}`, scheduled, actual, gap: actual != null ? actual - scheduled : null };
    });

    return { date, intervals };
  }

  // ── Violations report ───────────────────────────────────────────────────────
  async getViolationsReport(tenantId: string, from: string, to: string) {
    const rows = await this.dataSource.query(
      `SELECT v.*, e.employee_no,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name
       FROM agent_violations v
       LEFT JOIN employees e ON e.id = v.employee_id
       WHERE v.tenant_id = $1 AND v.violation_date BETWEEN $2::date AND $3::date
       ORDER BY v.violation_date DESC, v.severity DESC, v.minutes DESC NULLS LAST`,
      [tenantId, from, to],
    );

    const byType: Record<string, number> = {};
    const bySeverity: Record<string, number> = {};
    let openCount = 0;
    for (const r of rows) {
      byType[r.violation_type]  = (byType[r.violation_type]  ?? 0) + 1;
      bySeverity[r.severity]    = (bySeverity[r.severity]    ?? 0) + 1;
      if (r.status === 'open') openCount++;
    }

    // Repeat offenders (most violations in range)
    const topOffenders = Object.values(
      rows.reduce((m: Record<string, any>, r: any) => {
        const k = r.sprinklr_agent_id;
        m[k] = m[k] || { agentId: k, name: r.employee_name || r.agent_name, count: 0, totalMinutes: 0 };
        m[k].count++;
        m[k].totalMinutes += +r.minutes || 0;
        return m;
      }, {}),
    ).sort((a: any, b: any) => b.count - a.count).slice(0, 10);

    return { from, to, summary: { total: rows.length, open: openCount, byType, bySeverity }, topOffenders, rows };
  }

  async setViolationStatus(tenantId: string, id: string, status: string, reviewerId: string) {
    if (!['open', 'reviewed', 'justified'].includes(status)) status = 'reviewed';
    await this.dataSource.query(
      `UPDATE agent_violations
       SET status = $3, reviewed_by = $4, reviewed_at = NOW()
       WHERE tenant_id = $1 AND id = $2`,
      [tenantId, id, status, reviewerId],
    );
    return { ok: true };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  DAILY REPORT — per agent per day, joined with system employee via email
  // ═══════════════════════════════════════════════════════════════════════════
  async getAgentDailyReport(tenantId: string, from: string, to: string, refresh = false) {
    if (refresh) {
      // Recompute every day in range (bounded to 31 days)
      const start = new Date(from); const end = new Date(to);
      for (let d = new Date(start), i = 0; d <= end && i < 31; d.setDate(d.getDate() + 1), i++) {
        const ds = d.toISOString().slice(0, 10);
        await this.computeDailyStats(tenantId, ds);
        await this.computeViolations(tenantId, ds).catch(() => undefined);
      }
    }

    const rows = await this.dataSource.query(
      `SELECT s.stat_date, s.sprinklr_agent_id, s.agent_name, s.agent_email,
              s.employee_id,
              e.employee_no,
              TRIM(CONCAT(e.first_name_en, ' ', COALESCE(e.last_name_en,''))) AS employee_name,
              s.first_login, s.last_logout,
              s.total_working_minutes, s.idle_no_case_minutes, s.idle_with_case_minutes,
              s.busy_minutes, s.break_minutes, s.offline_minutes,
              s.contacts_received, s.aht_seconds, s.avg_response_seconds,
              s.status_minutes, s.extra, s.break_breakdown
       FROM agent_daily_stats s
       LEFT JOIN employees e ON e.id = s.employee_id
       WHERE s.tenant_id = $1 AND s.stat_date BETWEEN $2::date AND $3::date
       ORDER BY s.stat_date DESC, s.total_working_minutes DESC`,
      [tenantId, from, to],
    );

    // Per-day totals for the summary strip
    const byDate: Record<string, { agents: number; workingMinutes: number; contacts: number }> = {};
    for (const r of rows) {
      const d = String(r.stat_date).slice(0, 10);
      byDate[d] = byDate[d] || { agents: 0, workingMinutes: 0, contacts: 0 };
      byDate[d].agents++;
      byDate[d].workingMinutes += +r.total_working_minutes || 0;
      byDate[d].contacts       += +r.contacts_received     || 0;
    }

    return { from, to, days: byDate, rows };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  CONTACT FORECAST — weekday-seasonal moving average over daily history
  // ═══════════════════════════════════════════════════════════════════════════
  async getContactForecast(tenantId: string, daysAhead = 7) {
    // Two volume sources, take the stronger per day:
    //  1. agent_daily_stats.contacts_received (per-agent widget metrics)
    //  2. channel_demand_daily.contacts (queue cumulative counters — broader)
    const history: { stat_date: string; contacts: string; agents: string; working: string }[] =
      await this.dataSource.query(
        `SELECT d.stat_date,
                GREATEST(COALESCE(a.contacts, 0), COALESCE(q.contacts, 0)) AS contacts,
                COALESCE(a.agents, 0)  AS agents,
                COALESCE(a.working, 0) AS working
         FROM (
           SELECT DISTINCT stat_date FROM agent_daily_stats
           WHERE tenant_id = $1 AND stat_date >= CURRENT_DATE - INTERVAL '28 days'
           UNION
           SELECT DISTINCT demand_date FROM channel_demand_daily
           WHERE tenant_id = $1 AND demand_date >= CURRENT_DATE - INTERVAL '28 days'
         ) d(stat_date)
         LEFT JOIN (
           SELECT stat_date, SUM(contacts_received) AS contacts, COUNT(*) AS agents,
                  SUM(total_working_minutes) AS working
           FROM agent_daily_stats WHERE tenant_id = $1 GROUP BY stat_date
         ) a ON a.stat_date = d.stat_date
         LEFT JOIN (
           SELECT demand_date, SUM(contacts) AS contacts
           FROM channel_demand_daily WHERE tenant_id = $1 GROUP BY demand_date
         ) q ON q.demand_date = d.stat_date
         ORDER BY d.stat_date ASC`,
        [tenantId],
      );

    const hist = history.map(h => ({
      date:     String(h.stat_date).slice(0, 10),
      contacts: +h.contacts,
      agents:   +h.agents,
      workingMinutes: +h.working,
    }));

    const withData = hist.filter(h => h.contacts > 0);
    const overallAvg = withData.length
      ? withData.reduce((s, h) => s + h.contacts, 0) / withData.length : 0;

    // ── Methodology (Cleveland, "Call Center Management on Fast Forward"):
    //  - weekday seasonality index over trailing window
    //  - linear trend on day index (least squares)
    //  - P50 (median) and P90 bands per weekday — size staffing to P90, not P50
    //  - MAPE backtest (one-day-ahead) when ≥14 days to report honest accuracy
    const weekday: Record<number, number[]> = {};
    withData.forEach(h => {
      const wd = new Date(h.date).getDay();
      (weekday[wd] = weekday[wd] || []).push(h.contacts);
    });

    const pct = (arr: number[], p: number) => {
      if (!arr.length) return 0;
      const s = [...arr].sort((a, b) => a - b);
      const idx = Math.min(s.length - 1, Math.max(0, Math.ceil((p / 100) * s.length) - 1));
      return s[idx];
    };

    // Linear trend (least squares over day index)
    let slope = 0;
    if (withData.length >= 7) {
      const n = withData.length;
      const xs = withData.map((_, i) => i);
      const ys = withData.map(h => h.contacts);
      const xb = xs.reduce((a, b) => a + b, 0) / n;
      const yb = ys.reduce((a, b) => a + b, 0) / n;
      const num = xs.reduce((s, x, i) => s + (x - xb) * (ys[i] - yb), 0);
      const den = xs.reduce((s, x) => s + (x - xb) ** 2, 0);
      slope = den > 0 ? num / den : 0;
    }

    const forecast: {
      date: string; predictedContacts: number; p50: number; p90: number; method: string;
    }[] = [];
    for (let i = 1; i <= daysAhead; i++) {
      const d  = new Date(Date.now() + 3 * 3600e3 + i * 86400e3);
      const ds = d.toISOString().slice(0, 10);
      const wd = d.getDay();
      const wdVals = weekday[wd] ?? [];
      const base = wdVals.length
        ? wdVals.reduce((s, v) => s + v, 0) / wdVals.length
        : overallAvg;
      const trendAdj = slope * (withData.length - 1 + i);
      const predicted = Math.max(0, base + (withData.length >= 7 ? trendAdj - slope * (withData.length - 1) : 0));
      forecast.push({
        date: ds,
        predictedContacts: Math.round(predicted),
        p50: Math.round(wdVals.length ? pct(wdVals, 50) : overallAvg),
        p90: Math.round(wdVals.length ? pct(wdVals, 90) : overallAvg * 1.3),
        method: wdVals.length ? `weekday-seasonal+trend(${wdVals.length})` : 'overall-avg',
      });
    }

    // MAPE backtest: one-day-ahead naive-seasonal forecast vs actuals
    let mape: number | null = null;
    if (withData.length >= 14) {
      const errs: number[] = [];
      for (let i = 7; i < withData.length; i++) {
        const target = withData[i];
        const wd = new Date(target.date).getDay();
        const priorSame = withData.slice(0, i).filter(h => new Date(h.date).getDay() === wd);
        if (!priorSame.length || target.contacts === 0) continue;
        const pred = priorSame.reduce((s, h) => s + h.contacts, 0) / priorSame.length;
        errs.push(Math.abs(pred - target.contacts) / target.contacts);
      }
      if (errs.length) mape = +(100 * errs.reduce((a, b) => a + b, 0) / errs.length).toFixed(1);
    }

    return {
      history: hist,
      forecast,
      accuracy: { mape, backtestDays: withData.length >= 14 ? withData.length - 7 : 0,
                  note: 'MAPE = mean absolute % error of one-day-ahead backtest. <15% strong, <25% usable.' },
      confidence: withData.length >= 28 ? 'high'
                : withData.length >= 14 ? 'medium'
                : withData.length >= 7  ? 'low' : 'insufficient-data',
      sizingGuidance: 'Staff to P90, not the point forecast (Cleveland). P50 sizing misses SLA half the days.',
      note: withData.length < 7
        ? 'Need at least 7 days of contact data for a meaningful forecast. Forecast will improve as daily data accumulates.'
        : null,
    };
  }
}
