-- 066_schedule_drafts.sql
-- Saved DRAFT rosters generated by the demand-driven engine (roster-v2/generate-week/save).
-- A draft is a reviewable proposal (function × week × per-employee shift+OFF) held OUTSIDE the live
-- editable grid (attendance_records) — publishing into the live grid is a separate, confirmed step.
CREATE TABLE IF NOT EXISTS schedule_drafts (
  id          uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id   uuid        NOT NULL,
  function    text,
  week_start  date,
  label       text,
  payload     jsonb       NOT NULL,   -- {weekStart, function, days[], mix, staffing, warnings, grid:[{name,code,category,off,days[7]}]}
  created_by  uuid,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_schedule_drafts_tenant ON schedule_drafts(tenant_id, created_at DESC);
